/**
 * Backend OpenAPI schema mirror — generated fixture for the contract drift guard.
 *
 * Feature: beanola-production-readiness, Property 27: Frontend service shapes match the backend contract
 *
 * DO NOT EDIT BY HAND. Regenerate after backend API changes with:
 *   cd backend && DJANGO_SETTINGS_MODULE=config.settings.test \
 *     python3 manage.py spectacular --format openapi-json --file /tmp/openapi.json
 *   python3 backend/scripts/generate_openapi_fixture.py   # writes this file
 *
 * It captures the two facts the frontend half of Property 27 asserts:
 *  - the set of `/api/v1/...` route templates the schema exposes (route presence), and
 *  - every paginated `*Page` schema's property set (envelope/pagination shape).
 */

export const OPENAPI_SCHEMA_TITLE = "Beanola Platform APIs" as const

export const OPENAPI_PATHS: readonly string[] = [
  "/api/v1/admin/access-grants/",
  "/api/v1/admin/access-grants/{grant_id}/",
  "/api/v1/admin/audit-logs/",
  "/api/v1/admin/dashboard/",
  "/api/v1/admin/institutions/",
  "/api/v1/admin/institutions/{institution_id}/",
  "/api/v1/admin/institutions/{institution_id}/assets/",
  "/api/v1/admin/institutions/{institution_id}/assets/upload/",
  "/api/v1/admin/institutions/{institution_id}/assets/{item_id}/",
  "/api/v1/admin/institutions/{institution_id}/audit/",
  "/api/v1/admin/institutions/{institution_id}/document-profiles/",
  "/api/v1/admin/institutions/{institution_id}/document-profiles/{item_id}/",
  "/api/v1/admin/institutions/{institution_id}/document-profiles/{item_id}/clone/",
  "/api/v1/admin/institutions/{institution_id}/domains/",
  "/api/v1/admin/institutions/{institution_id}/domains/{item_id}/",
  "/api/v1/admin/institutions/{institution_id}/required-documents/",
  "/api/v1/admin/institutions/{institution_id}/required-documents/{item_id}/",
  "/api/v1/admin/institutions/{institution_id}/templates/",
  "/api/v1/admin/institutions/{institution_id}/templates/{item_id}/",
  "/api/v1/admin/memberships/",
  "/api/v1/admin/memberships/{membership_id}/",
  "/api/v1/admin/routing/simulate/",
  "/api/v1/admin/settings/",
  "/api/v1/admin/settings/import/",
  "/api/v1/admin/settings/reset/",
  "/api/v1/admin/settings/{id}/",
  "/api/v1/admin/templates/",
  "/api/v1/admin/templates/{key}/",
  "/api/v1/admin/tenant-audit/",
  "/api/v1/admin/users/",
  "/api/v1/admin/users/batch-import/",
  "/api/v1/admin/users/export/",
  "/api/v1/admin/users/{id}/",
  "/api/v1/analytics/funnel/",
  "/api/v1/analytics/outreach/",
  "/api/v1/analytics/sources/",
  "/api/v1/applications/",
  "/api/v1/applications/auto-assign/",
  "/api/v1/applications/bulk-status/",
  "/api/v1/applications/draft/",
  "/api/v1/applications/export/",
  "/api/v1/applications/history/",
  "/api/v1/applications/interviews/",
  "/api/v1/applications/track/",
  "/api/v1/applications/{application_id}/",
  "/api/v1/applications/{application_id}/acceptance-letter/",
  "/api/v1/applications/{application_id}/admin-summary/",
  "/api/v1/applications/{application_id}/amendments/",
  "/api/v1/applications/{application_id}/amendments/{amendment_id}/review/",
  "/api/v1/applications/{application_id}/application-slip/",
  "/api/v1/applications/{application_id}/assign/",
  "/api/v1/applications/{application_id}/conditional-offer/",
  "/api/v1/applications/{application_id}/conditions/",
  "/api/v1/applications/{application_id}/conditions/{condition_id}/verify/",
  "/api/v1/applications/{application_id}/confirm-enrollment/",
  "/api/v1/applications/{application_id}/details/",
  "/api/v1/applications/{application_id}/documents/",
  "/api/v1/applications/{application_id}/email-slip/",
  "/api/v1/applications/{application_id}/fee-waiver/",
  "/api/v1/applications/{application_id}/finance-receipt/",
  "/api/v1/applications/{application_id}/grades/",
  "/api/v1/applications/{application_id}/interviews/",
  "/api/v1/applications/{application_id}/official-documents/",
  "/api/v1/applications/{application_id}/official-documents/{document_type}/",
  "/api/v1/applications/{application_id}/payment-receipt/",
  "/api/v1/applications/{application_id}/preview-summary/",
  "/api/v1/applications/{application_id}/review/",
  "/api/v1/applications/{application_id}/submit/",
  "/api/v1/applications/{application_id}/summary/",
  "/api/v1/applications/{application_id}/verify-document/",
  "/api/v1/applications/{application_id}/waitlist-position/",
  "/api/v1/applications/{application_id}/withdraw/",
  "/api/v1/auth/login/",
  "/api/v1/auth/logout/",
  "/api/v1/auth/password-reset/",
  "/api/v1/auth/password-reset/confirm/",
  "/api/v1/auth/profile/",
  "/api/v1/auth/refresh/",
  "/api/v1/auth/register/",
  "/api/v1/auth/session/",
  "/api/v1/automation/rules/",
  "/api/v1/automation/runs/",
  "/api/v1/automation/runs/{run_id}/",
  "/api/v1/automation/runs/{run_id}/approve/",
  "/api/v1/automation/runs/{run_id}/cancel/",
  "/api/v1/catalog/assignment-preview/",
  "/api/v1/catalog/canonical-programs/",
  "/api/v1/catalog/context/",
  "/api/v1/catalog/institutions/",
  "/api/v1/catalog/institutions/{institution_id}/",
  "/api/v1/catalog/intakes/",
  "/api/v1/catalog/intakes/{intake_id}/",
  "/api/v1/catalog/programs/",
  "/api/v1/catalog/programs/{program_id}/",
  "/api/v1/catalog/subjects/",
  "/api/v1/documents/cover-letters/generate/",
  "/api/v1/documents/question-bank/answer/",
  "/api/v1/documents/resumes/",
  "/api/v1/documents/resumes/variants/",
  "/api/v1/documents/upload/",
  "/api/v1/documents/{document_id}/delete/",
  "/api/v1/documents/{document_id}/download/",
  "/api/v1/documents/{document_id}/extract/",
  "/api/v1/documents/{document_id}/info/",
  "/api/v1/documents/{document_id}/signed-url/",
  "/api/v1/documents/{document_id}/versions/",
  "/api/v1/email/accounts/zoho/connect/",
  "/api/v1/email/messages/",
  "/api/v1/email/send/",
  "/api/v1/email/threads/",
  "/api/v1/email/webhooks/delivery/",
  "/api/v1/errors/report/",
  "/api/v1/integrations/openai/test/",
  "/api/v1/integrations/telegram/connect/",
  "/api/v1/integrations/telegram/test/",
  "/api/v1/integrations/telegram/webhook/",
  "/api/v1/job-applications/",
  "/api/v1/job-applications/{application_id}/",
  "/api/v1/job-applications/{application_id}/approve/",
  "/api/v1/job-applications/{application_id}/pause/",
  "/api/v1/job-applications/{application_id}/reject/",
  "/api/v1/job-applications/{application_id}/resume/",
  "/api/v1/job-applications/{application_id}/submit/",
  "/api/v1/jobs/",
  "/api/v1/jobs/discovery-runs/",
  "/api/v1/jobs/discovery-runs/{run_id}/",
  "/api/v1/jobs/{job_id}/",
  "/api/v1/jobs/{job_id}/dismiss/",
  "/api/v1/jobs/{job_id}/score/",
  "/api/v1/jobs/{job_id}/tailor-documents/",
  "/api/v1/jobs/{job_id}/watch/",
  "/api/v1/meta/platform/",
  "/api/v1/notifications/",
  "/api/v1/notifications/mark-all-read/",
  "/api/v1/notifications/mark-read/",
  "/api/v1/notifications/preferences/",
  "/api/v1/notifications/read-all/",
  "/api/v1/notifications/user/{user_id}/",
  "/api/v1/notifications/{id}/",
  "/api/v1/notifications/{id}/read/",
  "/api/v1/outreach/campaigns/",
  "/api/v1/outreach/contacts/",
  "/api/v1/outreach/contacts/enrich/",
  "/api/v1/outreach/messages/generate/",
  "/api/v1/outreach/messages/send/",
  "/api/v1/payments/",
  "/api/v1/payments/defer/",
  "/api/v1/payments/dev-bypass/",
  "/api/v1/payments/initiate/",
  "/api/v1/payments/mobile-money/",
  "/api/v1/payments/resolve-fee/",
  "/api/v1/payments/risk-flags/",
  "/api/v1/payments/settlements/",
  "/api/v1/payments/webhook/lenco/",
  "/api/v1/payments/{payment_id}/correct/",
  "/api/v1/payments/{payment_id}/receipt/",
  "/api/v1/payments/{payment_id}/verify/",
  "/api/v1/programs/{program_id}/fees/",
  "/api/v1/programs/{program_id}/fees/{id}/",
  "/api/v1/reports/daily-digest/",
  "/api/v1/sessions/",
  "/api/v1/sessions/revoke-all/",
  "/api/v1/sessions/{session_id}/revoke/",
  "/health/live/",
  "/health/ready/",
  "/health/redis/",
] as const

export const OPENAPI_PAGE_SCHEMAS: Readonly<Record<string, readonly string[]>> = {
  "AdminAuditLogPage": ["page", "pageSize", "results", "totalCount"],
  "AdminNotificationHistoryPage": ["page", "pageSize", "results", "totalCount"],
  "AdminSettingPage": ["page", "pageSize", "results", "totalCount"],
  "AdminUserPage": ["page", "pageSize", "results", "totalCount"],
  "ApplicationListPage": ["page", "pageSize", "results", "totalCount"],
  "AutomationRulePage": ["page", "pageSize", "results", "totalCount"],
  "AutomationRunPage": ["page", "pageSize", "results", "totalCount"],
  "CatalogCanonicalProgramPage": ["page", "pageSize", "results", "totalCount"],
  "CatalogProgramPage": ["page", "pageSize", "results", "totalCount"],
  "EmailMessagePage": ["page", "pageSize", "results", "totalCount"],
  "EmailThreadPage": ["page", "pageSize", "results", "totalCount"],
  "JobApplicationPage": ["page", "pageSize", "results", "totalCount"],
  "JobsPage": ["page", "pageSize", "results", "totalCount"],
  "NotificationPage": ["page", "pageSize", "results", "totalCount"],
  "OutreachCampaignPage": ["page", "pageSize", "results", "totalCount"],
  "OutreachContactPage": ["page", "pageSize", "results", "totalCount"],
  "TimelineHistoryPage": ["page", "pageSize", "results", "totalCount"],
} as const
