"""Tests for the ``--check-migration-history-coverage`` flag on
``check_schema_drift``.

Task 4.2 of ``.kiro/specs/production-schema-reconciliation/`` extends
``check_schema_drift`` with two new argparse flags:

* ``--check-migration-history-coverage`` — enumerate
  ``backend/scripts/*.sql`` (top-level, excluding ``applied/``,
  ``archive/``, ``migrations/`` subdirectories and any
  ``*_rollback.sql`` sibling) and assert each forward-only script
  committed strictly more than ``--commit-window-days`` ago has a
  matching row in ``migration_history``.
* ``--commit-window-days`` — integer tolerance window (default 7).

Each gap surfaces as one of two canonical lines and contributes to a
non-zero exit:

* ``STALE_UNRECORDED_MIGRATION: <filename> committed=<iso8601>`` when
  ``git log`` returned a commit timestamp.
* ``UNTRACKED_MIGRATION_SCRIPT: <filename> source=mtime`` when the
  ``git`` lookup failed and the helper fell back to filesystem mtime.

The tests below cover the five behaviours called out in the task:

1. Flag absent — the helper is not invoked.
2. Stale unrecorded file — emits the canonical line and exits non-zero.
3. File within the commit window — tolerated, no line emitted.
4. File present in ``migration_history`` — tolerated, no line emitted.
5. Git failure fallback — emits ``UNTRACKED_MIGRATION_SCRIPT: ...
   source=mtime``.

Validates: Requirements 5.2, 5.3.
"""

from __future__ import annotations

import os
import time
from datetime import datetime, timedelta, timezone
from io import StringIO
from pathlib import Path

import pytest
from django.core.management import call_command
from django.db import connection


# Module-level marker so each test runs inside Django's test DB. The
# coverage helper queries ``migration_history`` directly, and the SQLite
# test DB does not have that table — the command's documented behaviour
# is to skip cleanly when the table is absent.
pytestmark = pytest.mark.django_db


# ---------------------------------------------------------------------------
# DDL helpers — build a minimal ``migration_history`` table that matches the
# post-extend shape so the coverage helper can read it.
# ---------------------------------------------------------------------------


_PG_DDL = """
CREATE TABLE migration_history (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    migration_name TEXT NOT NULL,
    applied_at TIMESTAMPTZ NULL,
    checksum TEXT NULL,
    notes TEXT NULL
);
CREATE UNIQUE INDEX uq_migration_history_migration_name
    ON migration_history (migration_name);
"""

_SQLITE_DDL = """
CREATE TABLE migration_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    migration_name TEXT NOT NULL,
    applied_at TEXT NULL,
    checksum TEXT NULL,
    notes TEXT NULL
);
CREATE UNIQUE INDEX uq_migration_history_migration_name
    ON migration_history (migration_name);
"""


def _drop_migration_history() -> None:
    with connection.cursor() as cur:
        cur.execute("DROP INDEX IF EXISTS uq_migration_history_migration_name")
        cur.execute("DROP TABLE IF EXISTS migration_history")


def _create_migration_history() -> None:
    ddl = _SQLITE_DDL if connection.vendor == "sqlite" else _PG_DDL
    with connection.cursor() as cur:
        for statement in ddl.split(";"):
            if statement.strip():
                cur.execute(statement)


@pytest.fixture
def migration_history_table():
    """Provide an isolated ``migration_history`` table with the extended shape.

    Drops any existing rows/table first so the test starts from a known
    blank state, builds the post-extend shape, then drops on teardown so
    later tests are not contaminated.
    """
    _drop_migration_history()
    _create_migration_history()
    yield
    _drop_migration_history()


@pytest.fixture
def scripts_dir(tmp_path: Path) -> Path:
    """Provide an isolated scripts directory the coverage helper will sweep.

    The default scripts directory (``backend/scripts/``) is shared across
    the whole repo and contains 10+ real Migration_Scripts at the time of
    writing — using it directly would either flake the tests (depending
    on git state) or paper over real production-readiness signals. The
    helper accepts an explicit ``directory`` parameter so each test
    builds its own fixture filesystem.
    """
    return tmp_path


def _write_sql(path: Path, body: str = "-- noop\n") -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body)
    return path


def _set_old_mtime(path: Path, days_ago: int) -> None:
    """Backdate ``path``'s mtime so the filesystem fallback flags it as stale.

    Used by the git-failure fallback test where we want
    ``_filesystem_mtime`` to return a value older than the commit
    window.
    """
    cutoff = time.time() - (days_ago * 86400)
    os.utime(path, (cutoff, cutoff))


# ---------------------------------------------------------------------------
# 1. Flag absent — helper is not invoked.
# ---------------------------------------------------------------------------


def test_flag_absent_does_not_invoke_coverage_helper(monkeypatch):
    """Without ``--check-migration-history-coverage``, the helper must not run.

    The coverage check enumerates the entire ``backend/scripts/``
    directory and shells out to ``git log`` per file. The contract is
    that operators who do not pass the flag pay none of that cost.
    Monkeypatching the helper to raise on call gives a sharp signal:
    any inadvertent invocation fails the test loudly.

    Validates: Requirement 5.2 (flag-gated activation).
    """
    from apps.common.management.commands import check_schema_drift

    def _boom(*args, **kwargs):
        raise AssertionError(
            "_find_stale_unrecorded_migrations was called even though "
            "--check-migration-history-coverage was not passed"
        )

    monkeypatch.setattr(
        check_schema_drift,
        "_find_stale_unrecorded_migrations",
        _boom,
    )

    out = StringIO()
    try:
        call_command("check_schema_drift", stdout=out)
    except SystemExit as exc:
        pytest.fail(
            f"check_schema_drift exited unexpectedly (code={exc.code}). "
            f"Output:\n{out.getvalue()}"
        )

    assert "No schema drift" in out.getvalue()


# ---------------------------------------------------------------------------
# 2. Stale unrecorded file — emits canonical line, exits non-zero.
# ---------------------------------------------------------------------------


def test_stale_unrecorded_migration_emits_canonical_line_and_exits_nonzero(
    migration_history_table, scripts_dir, monkeypatch,
):
    """A forward-only script committed > window days ago and missing
    from ``migration_history`` produces the canonical
    ``STALE_UNRECORDED_MIGRATION: <filename> committed=<iso8601>`` line
    and the command exits with code 1.

    The helper accepts a ``directory`` parameter so the test substitutes
    its own ``tmp_path`` for the real ``backend/scripts/`` and a fake
    ``_git_commit_timestamp`` so the test does not depend on a working
    ``git`` binary.

    Validates: Requirements 5.2, 5.3 (stale detection + canonical line).
    """
    from apps.common.management.commands import check_schema_drift

    stale_file = _write_sql(scripts_dir / "2024_01_01_old_migration.sql")
    fake_commit = datetime.now(timezone.utc) - timedelta(days=30)

    monkeypatch.setattr(
        check_schema_drift,
        "MIGRATION_SCRIPTS_DIR",
        scripts_dir,
    )
    monkeypatch.setattr(
        check_schema_drift,
        "_git_commit_timestamp",
        lambda path: fake_commit,
    )

    out = StringIO()
    with pytest.raises(SystemExit) as exc:
        call_command(
            "check_schema_drift",
            "--check-migration-history-coverage",
            stdout=out,
        )
    assert exc.value.code == 1, (
        f"Expected non-zero exit on stale unrecorded migration; got "
        f"{exc.value.code}. Output:\n{out.getvalue()}"
    )

    text = out.getvalue()
    expected_prefix = (
        f"STALE_UNRECORDED_MIGRATION: {stale_file.name} committed="
    )
    assert expected_prefix in text, (
        f"Expected canonical prefix {expected_prefix!r} in output. "
        f"Full output:\n{text}"
    )
    # The iso8601 timestamp is whatever the fake commit returned; the
    # canonical line shape uses the value as-is.
    assert fake_commit.isoformat() in text


# ---------------------------------------------------------------------------
# 3. File within commit window — tolerated, no canonical line emitted.
# ---------------------------------------------------------------------------


def test_file_within_commit_window_is_tolerated(
    migration_history_table, scripts_dir, monkeypatch,
):
    """A forward-only script committed within ``--commit-window-days``
    is treated as in-flight and does not produce a stale line.

    The default window is 7 days. We back-date the fake commit to 3 days
    ago — comfortably inside the window — and assert no canonical line
    appears for the file.

    Validates: Requirement 5.3 (commit-window tolerance).
    """
    from apps.common.management.commands import check_schema_drift

    in_flight_file = _write_sql(scripts_dir / "2026_05_22_in_flight.sql")
    fake_commit = datetime.now(timezone.utc) - timedelta(days=3)

    monkeypatch.setattr(
        check_schema_drift,
        "MIGRATION_SCRIPTS_DIR",
        scripts_dir,
    )
    monkeypatch.setattr(
        check_schema_drift,
        "_git_commit_timestamp",
        lambda path: fake_commit,
    )

    out = StringIO()
    try:
        call_command(
            "check_schema_drift",
            "--check-migration-history-coverage",
            stdout=out,
        )
    except SystemExit as exc:
        pytest.fail(
            f"check_schema_drift exited unexpectedly for an in-flight "
            f"migration (code={exc.code}). Output:\n{out.getvalue()}"
        )

    text = out.getvalue()
    assert "STALE_UNRECORDED_MIGRATION" not in text, (
        f"In-flight migration {in_flight_file.name} should not produce "
        f"a STALE_UNRECORDED_MIGRATION line. Output:\n{text}"
    )
    assert "UNTRACKED_MIGRATION_SCRIPT" not in text


# ---------------------------------------------------------------------------
# 4. File present in migration_history — tolerated, no line emitted.
# ---------------------------------------------------------------------------


def test_recorded_migration_is_tolerated(
    migration_history_table, scripts_dir, monkeypatch,
):
    """A script whose basename appears in ``migration_history`` is
    skipped, even when its commit timestamp is far older than the
    commit window.

    The contract: ``migration_history`` is the source of truth for what
    has been applied. The check exists to flag forward-only files that
    the operator has not yet recorded — once recorded, the file is no
    longer the check's concern regardless of its age.

    Validates: Requirement 5.3 (presence-in-migration_history takes
    precedence over commit-age).
    """
    from apps.common.management.commands import check_schema_drift

    recorded_file = _write_sql(scripts_dir / "2024_01_01_recorded.sql")

    # Record the file in migration_history. The fake commit is older
    # than the window so without the recorded-row exclusion the helper
    # would otherwise flag it as stale.
    with connection.cursor() as cur:
        cur.execute(
            "INSERT INTO migration_history (migration_name, applied_at, "
            "checksum, notes) VALUES (%s, %s, %s, %s)",
            [
                recorded_file.name,
                "2024-01-01T00:00:00+00:00",
                "deadbeef",
                "test fixture",
            ],
        )

    fake_commit = datetime.now(timezone.utc) - timedelta(days=30)
    monkeypatch.setattr(
        check_schema_drift,
        "MIGRATION_SCRIPTS_DIR",
        scripts_dir,
    )
    monkeypatch.setattr(
        check_schema_drift,
        "_git_commit_timestamp",
        lambda path: fake_commit,
    )

    out = StringIO()
    try:
        call_command(
            "check_schema_drift",
            "--check-migration-history-coverage",
            stdout=out,
        )
    except SystemExit as exc:
        pytest.fail(
            f"check_schema_drift exited unexpectedly for a recorded "
            f"migration (code={exc.code}). Output:\n{out.getvalue()}"
        )

    text = out.getvalue()
    assert "STALE_UNRECORDED_MIGRATION" not in text, (
        f"Recorded migration {recorded_file.name} should not produce "
        f"a STALE_UNRECORDED_MIGRATION line. Output:\n{text}"
    )
    assert "UNTRACKED_MIGRATION_SCRIPT" not in text


# ---------------------------------------------------------------------------
# 5. Git failure fallback — emits UNTRACKED_MIGRATION_SCRIPT canonical line.
# ---------------------------------------------------------------------------


def test_git_failure_falls_back_to_mtime_and_emits_untracked_line(
    migration_history_table, scripts_dir, monkeypatch,
):
    """When ``git log`` returns nothing (shallow clone, missing binary,
    untracked file), the helper falls back to filesystem mtime and
    emits the ``UNTRACKED_MIGRATION_SCRIPT: <filename> source=mtime``
    canonical line.

    This is the R5.3 fallback contract: the line shape's distinct
    prefix lets CI log parsers and runbooks branch on whether git knew
    the file's age or not.

    Validates: Requirement 5.3 (git failure fallback + canonical line).
    """
    from apps.common.management.commands import check_schema_drift

    untracked_file = _write_sql(scripts_dir / "2026_01_01_untracked.sql")
    # Backdate the file so the mtime fallback flags it as stale.
    _set_old_mtime(untracked_file, days_ago=30)

    monkeypatch.setattr(
        check_schema_drift,
        "MIGRATION_SCRIPTS_DIR",
        scripts_dir,
    )
    # Simulate ``git log`` failure for every path — the helper's
    # contract is to return ``None`` from ``_git_commit_timestamp`` on
    # any error, and the caller must fall back to mtime.
    monkeypatch.setattr(
        check_schema_drift,
        "_git_commit_timestamp",
        lambda path: None,
    )

    out = StringIO()
    with pytest.raises(SystemExit) as exc:
        call_command(
            "check_schema_drift",
            "--check-migration-history-coverage",
            stdout=out,
        )
    assert exc.value.code == 1, (
        f"Expected non-zero exit on stale untracked migration; got "
        f"{exc.value.code}. Output:\n{out.getvalue()}"
    )

    text = out.getvalue()
    expected = (
        f"UNTRACKED_MIGRATION_SCRIPT: {untracked_file.name} source=mtime"
    )
    assert expected in text, (
        f"Expected fallback canonical line {expected!r} in output. "
        f"Full output:\n{text}"
    )
    # The git-known prefix must NOT appear for this file — the
    # fallback path is mutually exclusive with the git path.
    assert "STALE_UNRECORDED_MIGRATION" not in text


# ---------------------------------------------------------------------------
# Helper-level test: rollback siblings and excluded subdirs are filtered out.
# ---------------------------------------------------------------------------


def test_enumerate_migration_scripts_excludes_rollback_and_subdirs(scripts_dir):
    """``_enumerate_migration_scripts`` returns only top-level forward
    Migration_Scripts.

    Three things are filtered out:

    * ``*_rollback.sql`` siblings (every forward script ships with one;
      the coverage rule applies to forward scripts only).
    * Files inside ``applied/``, ``archive/``, and ``migrations/``
      subdirectories (the helper does not recurse).
    * Non-``.sql`` files (README, .py helpers).

    Validates: Requirement 5.2 (correct enumeration scope).
    """
    from apps.common.management.commands.check_schema_drift import (
        _enumerate_migration_scripts,
    )

    forward = _write_sql(scripts_dir / "2026_05_18_forward.sql")
    _write_sql(scripts_dir / "2026_05_18_forward_rollback.sql")
    _write_sql(scripts_dir / "applied" / "already_applied.sql")
    _write_sql(scripts_dir / "archive" / "old_one.sql")
    _write_sql(scripts_dir / "migrations" / "legacy_one.sql")
    (scripts_dir / "README.md").write_text("# scripts directory")
    (scripts_dir / "helper.py").write_text("# python helper")

    found = _enumerate_migration_scripts(scripts_dir)
    names = [p.name for p in found]
    assert names == [forward.name], (
        f"Expected only the top-level forward script; got {names!r}"
    )


# ---------------------------------------------------------------------------
# Helper-level test: missing migration_history table is a clean skip.
# ---------------------------------------------------------------------------


def test_coverage_check_skips_when_migration_history_missing(
    scripts_dir, monkeypatch,
):
    """When the configured DB has no ``migration_history`` table, the
    coverage check skips with a warning and returns success.

    This mirrors the FK-index Postgres-only skip path: the contract is
    that a flag-on test run on an unconfigured database stays green.
    A SQLite test DB without the bootstrap migration is the canonical
    use-case.

    Validates: Requirement 5.2 (graceful skip when bootstrap missing).
    """
    from apps.common.management.commands import check_schema_drift

    # Make sure the table genuinely is not present (other tests may
    # have left it behind via the fixture's teardown).
    _drop_migration_history()

    _write_sql(scripts_dir / "2024_01_01_old.sql")
    monkeypatch.setattr(
        check_schema_drift,
        "MIGRATION_SCRIPTS_DIR",
        scripts_dir,
    )
    monkeypatch.setattr(
        check_schema_drift,
        "_git_commit_timestamp",
        lambda path: datetime.now(timezone.utc) - timedelta(days=30),
    )

    out = StringIO()
    try:
        call_command(
            "check_schema_drift",
            "--check-migration-history-coverage",
            stdout=out,
        )
    except SystemExit as exc:
        pytest.fail(
            f"check_schema_drift should not have exited when "
            f"migration_history is missing. code={exc.code} "
            f"output:\n{out.getvalue()}"
        )

    text = out.getvalue()
    assert "--check-migration-history-coverage skipped" in text, (
        f"Expected a clear skip message; got:\n{text}"
    )
    assert "STALE_UNRECORDED_MIGRATION" not in text
    assert "UNTRACKED_MIGRATION_SCRIPT" not in text
