"""Tests for the additive-only SQL lint in ``apply_sql_migrations``.

Task 1.5 of ``.kiro/specs/production-schema-reconciliation/`` extends
``apply_sql_migrations`` with a pre-execution lint that scans each
migration file's body and rejects non-additive operations:

* ``DROP COLUMN``
* ``DROP TABLE``
* ``TRUNCATE``
* ``DELETE FROM`` without a ``WHERE`` clause in the same statement
* ``ALTER TABLE ... ALTER COLUMN ... TYPE ... USING`` (narrowing
  conversions)

The lint runs after stripping ``--`` line comments and ``/* ... */``
block comments. The operator can opt out with ``--allow-non-additive``.

These tests exercise:

1. The pure ``_find_non_additive_violations`` helper for each pattern,
   including comment-aware behaviour and the "DELETE without WHERE"
   per-statement scoping rule.
2. The ``apply_sql_migrations`` command rejecting a non-additive file
   with the canonical ``REJECTED_NON_ADDITIVE_OPERATION:`` line and a
   non-zero exit code (CommandError).
3. The ``--allow-non-additive`` bypass letting the same file apply
   successfully.
4. Comment-only mentions (e.g. ``-- DROP COLUMN ...``) NOT triggering
   the lint.
5. Additive scripts (``CREATE TABLE``, ``ADD COLUMN``,
   ``CREATE INDEX``) passing through cleanly.

The tests reuse the same SQLite-friendly extended ``migration_history``
shape as ``test_apply_sql_migrations.py`` so they run on the local CI
without needing a Postgres connection.

Validates: Requirement 1.2.
"""
from __future__ import annotations

from io import StringIO
from pathlib import Path

import pytest
from django.core.management import call_command
from django.core.management.base import CommandError
from django.db import connection

from apps.common.management.commands.apply_sql_migrations import (
    _find_non_additive_violations,
    _strip_sql_comments,
)


# ---------------------------------------------------------------------------
# DDL helpers — match the post-extend ``migration_history`` shape used by
# the existing apply_sql_migrations test module so the same fixtures work
# on both SQLite and Postgres.
# ---------------------------------------------------------------------------

_PG_EXTENDED_DDL = """
CREATE TABLE migration_history (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    migration_name TEXT NOT NULL,
    applied_at TIMESTAMPTZ NULL,
    checksum TEXT NULL,
    notes TEXT NULL
);
CREATE UNIQUE INDEX uq_migration_history_migration_name
    ON migration_history (migration_name);
"""

_SQLITE_EXTENDED_DDL = """
CREATE TABLE migration_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    migration_name TEXT NOT NULL,
    applied_at TEXT NULL,
    checksum TEXT NULL,
    notes TEXT NULL
);
CREATE UNIQUE INDEX uq_migration_history_migration_name
    ON migration_history (migration_name);
"""


def _drop_migration_history() -> None:
    with connection.cursor() as cur:
        cur.execute("DROP INDEX IF EXISTS uq_migration_history_migration_name")
        cur.execute("DROP TABLE IF EXISTS migration_history")


def _create_extended_migration_history() -> None:
    ddl = _SQLITE_EXTENDED_DDL if connection.vendor == "sqlite" else _PG_EXTENDED_DDL
    with connection.cursor() as cur:
        for statement in [s.strip() for s in ddl.split(";") if s.strip()]:
            cur.execute(statement)


@pytest.fixture
def fresh_migration_history():
    _drop_migration_history()
    _create_extended_migration_history()
    yield
    _drop_migration_history()


@pytest.fixture
def migrations_dir(tmp_path):
    d = tmp_path / "scripts"
    d.mkdir()
    return d


def _write(path: Path, sql: str) -> None:
    path.write_text(sql)


# ---------------------------------------------------------------------------
# Pure-function tests for ``_find_non_additive_violations``
# ---------------------------------------------------------------------------


class TestFindNonAdditiveViolations:
    """The pure lint helper detects every pattern the spec calls out."""

    def test_clean_additive_sql_returns_no_violations(self):
        sql = (
            "CREATE TABLE IF NOT EXISTS foo (id INT PRIMARY KEY);\n"
            "ALTER TABLE bar ADD COLUMN IF NOT EXISTS baz TEXT NULL;\n"
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_foo_id ON foo(id);\n"
            "INSERT INTO seed (id, name) VALUES (1, 'a') "
            "ON CONFLICT (id) DO NOTHING;\n"
        )
        assert _find_non_additive_violations(sql) == []

    def test_drop_column_is_rejected(self):
        sql = "ALTER TABLE foo DROP COLUMN bar;"
        assert "DROP COLUMN" in _find_non_additive_violations(sql)

    def test_drop_table_is_rejected(self):
        sql = "DROP TABLE foo;"
        assert "DROP TABLE" in _find_non_additive_violations(sql)

    def test_truncate_is_rejected(self):
        sql = "TRUNCATE TABLE foo;"
        assert "TRUNCATE" in _find_non_additive_violations(sql)

    def test_delete_from_without_where_is_rejected(self):
        sql = "DELETE FROM foo;"
        assert "DELETE FROM (without WHERE)" in _find_non_additive_violations(sql)

    def test_delete_from_with_where_is_allowed(self):
        sql = "DELETE FROM foo WHERE id = 5;"
        violations = _find_non_additive_violations(sql)
        assert "DELETE FROM (without WHERE)" not in violations

    def test_delete_from_with_where_in_separate_statement_still_rejected(self):
        """A bare DELETE in one statement is rejected even if a later
        DELETE is bounded — each ``;``-terminated scope is checked
        independently to match operator intuition.
        """
        sql = (
            "DELETE FROM foo;\n"
            "DELETE FROM bar WHERE id = 1;\n"
        )
        assert "DELETE FROM (without WHERE)" in _find_non_additive_violations(sql)

    def test_alter_column_type_using_is_rejected(self):
        sql = (
            "ALTER TABLE foo ALTER COLUMN bar "
            "TYPE INTEGER USING bar::integer;"
        )
        assert "ALTER COLUMN TYPE USING" in _find_non_additive_violations(sql)

    def test_widening_alter_column_type_without_using_is_allowed(self):
        """A widening conversion (no USING clause) is permitted by the
        spec — only narrowing conversions with explicit ``USING`` are
        rejected.
        """
        sql = "ALTER TABLE foo ALTER COLUMN bar TYPE BIGINT;"
        assert _find_non_additive_violations(sql) == []

    def test_drop_column_in_line_comment_is_ignored(self):
        sql = (
            "-- DROP COLUMN bar (planned for future migration)\n"
            "ALTER TABLE foo ADD COLUMN baz TEXT NULL;\n"
        )
        assert _find_non_additive_violations(sql) == []

    def test_drop_table_in_block_comment_is_ignored(self):
        sql = (
            "/* DROP TABLE foo;\n"
            "   This is documentation explaining future cleanup. */\n"
            "CREATE TABLE bar (id INT PRIMARY KEY);\n"
        )
        assert _find_non_additive_violations(sql) == []

    def test_truncate_in_inline_comment_is_ignored(self):
        sql = "SELECT 1; -- TRUNCATE planned for next quarter\n"
        assert _find_non_additive_violations(sql) == []

    def test_case_insensitive_detection(self):
        sql = "drop table foo;"
        assert "DROP TABLE" in _find_non_additive_violations(sql)

    def test_multiple_violations_are_all_reported(self):
        sql = (
            "DROP TABLE foo;\n"
            "TRUNCATE bar;\n"
            "ALTER TABLE baz DROP COLUMN qux;\n"
        )
        violations = _find_non_additive_violations(sql)
        assert "DROP TABLE" in violations
        assert "TRUNCATE" in violations
        assert "DROP COLUMN" in violations


class TestStripSqlComments:
    """The block + line comment stripper feeds the lint."""

    def test_strips_line_comments(self):
        cleaned = _strip_sql_comments("SELECT 1; -- comment\n")
        assert "comment" not in cleaned

    def test_strips_block_comments(self):
        cleaned = _strip_sql_comments("SELECT 1; /* block comment */ SELECT 2;")
        assert "block comment" not in cleaned
        assert "SELECT 1" in cleaned and "SELECT 2" in cleaned

    def test_strips_multiline_block_comments(self):
        sql = "/* line 1\nline 2\nline 3 */\nSELECT 1;"
        cleaned = _strip_sql_comments(sql)
        assert "line 1" not in cleaned
        assert "SELECT 1" in cleaned


# ---------------------------------------------------------------------------
# Integration tests against the management command
# ---------------------------------------------------------------------------


@pytest.mark.django_db
class TestApplySqlMigrationsLint:
    """The command rejects non-additive files unless the bypass flag is set."""

    def test_drop_column_file_is_rejected_with_canonical_message(
        self, fresh_migration_history, migrations_dir
    ):
        _write(
            migrations_dir / "0001_drop_column.sql",
            "ALTER TABLE foo DROP COLUMN bar;",
        )

        out, err = StringIO(), StringIO()
        with pytest.raises(CommandError) as exc:
            call_command(
                "apply_sql_migrations",
                "--migrations-dir",
                str(migrations_dir),
                stdout=out,
                stderr=err,
            )

        assert (
            "REJECTED_NON_ADDITIVE_OPERATION: DROP COLUMN in 0001_drop_column.sql"
            in err.getvalue()
        )
        # CommandError carries the same offending pattern for log surfaces.
        assert "DROP COLUMN" in str(exc.value)

        # No row should have been written into ``migration_history``
        # because the file was rejected pre-execution.
        with connection.cursor() as cur:
            cur.execute("SELECT COUNT(*) FROM migration_history")
            assert cur.fetchone()[0] == 0

    def test_drop_table_file_is_rejected(
        self, fresh_migration_history, migrations_dir
    ):
        _write(migrations_dir / "0001_drop_table.sql", "DROP TABLE foo;")

        err = StringIO()
        with pytest.raises(CommandError):
            call_command(
                "apply_sql_migrations",
                "--migrations-dir",
                str(migrations_dir),
                stdout=StringIO(),
                stderr=err,
            )

        assert (
            "REJECTED_NON_ADDITIVE_OPERATION: DROP TABLE in 0001_drop_table.sql"
            in err.getvalue()
        )

    def test_truncate_file_is_rejected(
        self, fresh_migration_history, migrations_dir
    ):
        _write(migrations_dir / "0001_truncate.sql", "TRUNCATE TABLE foo;")

        err = StringIO()
        with pytest.raises(CommandError):
            call_command(
                "apply_sql_migrations",
                "--migrations-dir",
                str(migrations_dir),
                stdout=StringIO(),
                stderr=err,
            )

        assert (
            "REJECTED_NON_ADDITIVE_OPERATION: TRUNCATE in 0001_truncate.sql"
            in err.getvalue()
        )

    def test_unbounded_delete_file_is_rejected(
        self, fresh_migration_history, migrations_dir
    ):
        _write(migrations_dir / "0001_delete.sql", "DELETE FROM foo;")

        err = StringIO()
        with pytest.raises(CommandError):
            call_command(
                "apply_sql_migrations",
                "--migrations-dir",
                str(migrations_dir),
                stdout=StringIO(),
                stderr=err,
            )

        assert (
            "REJECTED_NON_ADDITIVE_OPERATION: DELETE FROM (without WHERE) "
            "in 0001_delete.sql"
            in err.getvalue()
        )

    def test_bounded_delete_file_is_allowed(
        self, fresh_migration_history, migrations_dir
    ):
        """A ``DELETE ... WHERE`` is a permitted targeted cleanup
        (used by, e.g., the migration_history reconcile rollback).
        """
        # First create the table the DELETE will target so the SQL
        # actually executes cleanly on SQLite.
        with connection.cursor() as cur:
            cur.execute(
                "CREATE TABLE IF NOT EXISTS _aux_lint_delete "
                "(id INT PRIMARY KEY, name TEXT)"
            )
            cur.execute("INSERT INTO _aux_lint_delete VALUES (1, 'a')")

        _write(
            migrations_dir / "0001_bounded_delete.sql",
            "DELETE FROM _aux_lint_delete WHERE id = 999;",
        )

        call_command(
            "apply_sql_migrations",
            "--migrations-dir",
            str(migrations_dir),
            stdout=StringIO(),
        )

        with connection.cursor() as cur:
            cur.execute(
                "SELECT migration_name FROM migration_history "
                "WHERE migration_name = %s",
                ["0001_bounded_delete.sql"],
            )
            assert cur.fetchone() is not None
            cur.execute("DROP TABLE IF EXISTS _aux_lint_delete")

    def test_alter_column_type_using_file_is_rejected(
        self, fresh_migration_history, migrations_dir
    ):
        _write(
            migrations_dir / "0001_alter_using.sql",
            "ALTER TABLE foo ALTER COLUMN bar TYPE INTEGER USING bar::integer;",
        )

        err = StringIO()
        with pytest.raises(CommandError):
            call_command(
                "apply_sql_migrations",
                "--migrations-dir",
                str(migrations_dir),
                stdout=StringIO(),
                stderr=err,
            )

        assert (
            "REJECTED_NON_ADDITIVE_OPERATION: ALTER COLUMN TYPE USING "
            "in 0001_alter_using.sql"
            in err.getvalue()
        )

    def test_allow_non_additive_flag_bypasses_lint(
        self, fresh_migration_history, migrations_dir
    ):
        """``--allow-non-additive`` lets a DROP-flavoured file apply."""
        # Create a target table the DROP will operate against so the
        # SQL itself is valid, otherwise the test would fail for a
        # different reason than the lint.
        with connection.cursor() as cur:
            cur.execute(
                "CREATE TABLE IF NOT EXISTS _aux_lint_bypass "
                "(id INT PRIMARY KEY, doomed TEXT)"
            )

        if connection.vendor == "sqlite":
            # SQLite supports ``ALTER TABLE ... DROP COLUMN`` only
            # since 3.35; the syntax is otherwise the same. Use a
            # ``DROP TABLE`` payload which works on every supported
            # vendor.
            sql = "DROP TABLE _aux_lint_bypass;"
        else:
            sql = "ALTER TABLE _aux_lint_bypass DROP COLUMN doomed;"

        _write(migrations_dir / "0001_bypass.sql", sql)

        out = StringIO()
        call_command(
            "apply_sql_migrations",
            "--migrations-dir",
            str(migrations_dir),
            "--allow-non-additive",
            stdout=out,
        )

        with connection.cursor() as cur:
            cur.execute(
                "SELECT migration_name FROM migration_history "
                "WHERE migration_name = %s",
                ["0001_bypass.sql"],
            )
            assert cur.fetchone() is not None
            cur.execute("DROP TABLE IF EXISTS _aux_lint_bypass")

    def test_dry_run_still_rejects_non_additive_file(
        self, fresh_migration_history, migrations_dir
    ):
        """Operators planning a release see the rejection during
        ``--dry-run`` so they can re-author the file before the
        maintenance window.
        """
        _write(
            migrations_dir / "0001_drop_column_dry.sql",
            "ALTER TABLE foo DROP COLUMN bar;",
        )

        err = StringIO()
        with pytest.raises(CommandError):
            call_command(
                "apply_sql_migrations",
                "--migrations-dir",
                str(migrations_dir),
                "--dry-run",
                stdout=StringIO(),
                stderr=err,
            )

        assert (
            "REJECTED_NON_ADDITIVE_OPERATION: DROP COLUMN "
            "in 0001_drop_column_dry.sql"
            in err.getvalue()
        )

    def test_clean_additive_file_passes(
        self, fresh_migration_history, migrations_dir
    ):
        """A baseline regression: a fully additive file must apply
        cleanly with the lint enabled.
        """
        _write(
            migrations_dir / "0001_clean.sql",
            "CREATE TABLE IF NOT EXISTS _aux_lint_clean (id INT PRIMARY KEY);",
        )

        call_command(
            "apply_sql_migrations",
            "--migrations-dir",
            str(migrations_dir),
            stdout=StringIO(),
        )

        with connection.cursor() as cur:
            cur.execute(
                "SELECT migration_name FROM migration_history "
                "WHERE migration_name = %s",
                ["0001_clean.sql"],
            )
            assert cur.fetchone() is not None
            cur.execute("DROP TABLE IF EXISTS _aux_lint_clean")

    def test_drop_column_in_comment_does_not_trigger_lint(
        self, fresh_migration_history, migrations_dir
    ):
        """A documentation comment mentioning a future drop must not
        be confused for an actual non-additive operation.
        """
        _write(
            migrations_dir / "0001_comment_only.sql",
            "-- DROP COLUMN bar (planned 2026-08-15)\n"
            "/* TRUNCATE planned for legacy table */\n"
            "CREATE TABLE IF NOT EXISTS _aux_lint_comment "
            "(id INT PRIMARY KEY);\n",
        )

        call_command(
            "apply_sql_migrations",
            "--migrations-dir",
            str(migrations_dir),
            stdout=StringIO(),
        )

        with connection.cursor() as cur:
            cur.execute(
                "SELECT migration_name FROM migration_history "
                "WHERE migration_name = %s",
                ["0001_comment_only.sql"],
            )
            assert cur.fetchone() is not None
            cur.execute("DROP TABLE IF EXISTS _aux_lint_comment")
