"""Tests for the structured ``OK:`` success line on ``check_schema_drift``.

Task 4.3 of ``.kiro/specs/production-schema-reconciliation/`` updates the
success path so that — when at least one of ``--check-fk-indexes`` or
``--check-migration-history-coverage`` is passed — the command prints a
single structured line of the form::

    OK: schema-drift=<n> fk-indexes=<m> migration-history=<k>

where:

* ``<n>`` is the count of ``managed=False`` models verified by the
  existing default check.
* ``<m>`` is the count of foreign-key columns inspected when
  ``--check-fk-indexes`` is passed; the literal ``disabled`` otherwise
  (or when the helper short-circuits — non-Postgres backends today).
* ``<k>`` is the count of Migration_Scripts inspected when
  ``--check-migration-history-coverage`` is passed; the literal
  ``disabled`` otherwise (or when the helper short-circuits — missing
  ``migration_history`` table on the configured DB).

The pre-existing "No schema drift. Verified <n> managed=False model(s)."
line is preserved verbatim for the no-flag case so existing CI log
parsers, runbooks, and the prior test suite stay green.

The tests below cover the four behaviours called out in Task 4.3:

1. **Default invocation** (no new flags) — historical line preserved.
2. **``--check-fk-indexes`` only** — structured line shows the FK count
   and ``migration-history=disabled``.
3. **Both flags** — structured line shows both counts.
4. **``--check-fk-indexes`` skipped on SQLite with the flag passed** —
   ``fk-indexes=disabled`` is emitted because the helper short-circuited
   on the non-Postgres backend.

Validates: Requirement 5.6.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from io import StringIO
from pathlib import Path

import pytest
from django.core.management import call_command
from django.db import connection


# Module-level marker — every test here goes through Django's test DB
# layer (the management command opens a connection during ``call_command``
# even for paths that do not query). The SQLite backend is the canonical
# test environment; that is what exercises the ``disabled`` short-circuit
# for ``--check-fk-indexes``.
pytestmark = pytest.mark.django_db


# ---------------------------------------------------------------------------
# DDL helpers — copied from
# ``test_check_schema_drift_migration_history_coverage.py`` so we can
# build a minimal ``migration_history`` table that matches the
# post-extend shape expected by ``--check-migration-history-coverage``.
# ---------------------------------------------------------------------------


_PG_DDL = """
CREATE TABLE migration_history (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    migration_name TEXT NOT NULL,
    applied_at TIMESTAMPTZ NULL,
    checksum TEXT NULL,
    notes TEXT NULL
);
CREATE UNIQUE INDEX uq_migration_history_migration_name
    ON migration_history (migration_name);
"""

_SQLITE_DDL = """
CREATE TABLE migration_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    migration_name TEXT NOT NULL,
    applied_at TEXT NULL,
    checksum TEXT NULL,
    notes TEXT NULL
);
CREATE UNIQUE INDEX uq_migration_history_migration_name
    ON migration_history (migration_name);
"""


def _drop_migration_history() -> None:
    with connection.cursor() as cur:
        cur.execute("DROP INDEX IF EXISTS uq_migration_history_migration_name")
        cur.execute("DROP TABLE IF EXISTS migration_history")


def _create_migration_history() -> None:
    ddl = _SQLITE_DDL if connection.vendor == "sqlite" else _PG_DDL
    with connection.cursor() as cur:
        for statement in ddl.split(";"):
            if statement.strip():
                cur.execute(statement)


@pytest.fixture
def migration_history_table():
    """Provide an isolated ``migration_history`` table.

    Used by the both-flags case so the migration-history coverage helper
    finds the bootstrap table and reports a numeric count rather than
    the ``disabled`` short-circuit.
    """
    _drop_migration_history()
    _create_migration_history()
    yield
    _drop_migration_history()


def _write_sql(path: Path, body: str = "-- noop\n") -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body)
    return path


# ---------------------------------------------------------------------------
# 1. Default invocation — preserved historical line, no structured OK.
# ---------------------------------------------------------------------------


def test_default_invocation_preserves_historical_success_line():
    """Without the new flags, the success line is unchanged.

    R5.6 explicitly requires backwards compatibility for the no-flag
    case so existing CI log parsers and runbooks keep working without
    edits. The structured ``OK:`` form must NOT appear on this path.

    Validates: Requirement 5.6 (backwards compat).
    """
    out = StringIO()
    try:
        call_command("check_schema_drift", stdout=out)
    except SystemExit as exc:
        # If the live schema has unrelated drift, surface it loudly so
        # the test author can fix the schema rather than the test.
        pytest.fail(
            f"check_schema_drift exited unexpectedly (code={exc.code}). "
            f"Output:\n{out.getvalue()}"
        )

    text = out.getvalue()
    assert "No schema drift. Verified " in text, (
        f"Expected the historical success line; got:\n{text}"
    )
    assert "managed=False model(s)." in text
    # The structured OK line must not leak onto the default path.
    assert "OK: schema-drift=" not in text


# ---------------------------------------------------------------------------
# 2. --check-fk-indexes only — structured line + migration-history=disabled.
# ---------------------------------------------------------------------------


def test_fk_indexes_only_emits_structured_ok_with_migration_history_disabled():
    """Passing only ``--check-fk-indexes`` produces the structured
    ``OK:`` line; ``migration-history=disabled`` reflects the omitted
    flag.

    On the SQLite test backend the FK-index helper short-circuits with
    a Postgres-only skip, so ``fk-indexes=disabled`` is also expected
    here. The historical "No schema drift" line must NOT appear on
    this path — once any new flag is passed, the structured form is
    the contract.

    Validates: Requirement 5.6 (structured line, disabled token for
    omitted flags).
    """
    out = StringIO()
    try:
        call_command(
            "check_schema_drift",
            "--check-fk-indexes",
            stdout=out,
        )
    except SystemExit as exc:
        pytest.fail(
            f"check_schema_drift exited unexpectedly with "
            f"--check-fk-indexes (code={exc.code}). Output:\n{out.getvalue()}"
        )

    text = out.getvalue()
    assert "OK: schema-drift=" in text, (
        f"Expected structured OK line; got:\n{text}"
    )
    assert "fk-indexes=" in text
    assert "migration-history=disabled" in text, (
        f"Expected migration-history=disabled when the flag is omitted; "
        f"got:\n{text}"
    )
    # Historical line must NOT appear when the structured form is in
    # play — that would defeat the point of giving CI parsers a single
    # canonical shape to grep for.
    assert "No schema drift. Verified" not in text


# ---------------------------------------------------------------------------
# 3. Both flags — structured line shows both counts.
# ---------------------------------------------------------------------------


def test_both_flags_emit_structured_ok_with_both_counts(
    migration_history_table, tmp_path, monkeypatch,
):
    """Passing both new flags produces the structured ``OK:`` line with
    a numeric count for ``migration-history=`` (because the bootstrap
    table now exists) and ``fk-indexes=disabled`` (because the test DB
    is SQLite and the FK-index helper short-circuits).

    The migration-history count reflects the number of forward-only
    Migration_Scripts the helper inspected. The test substitutes a
    tmp_path-rooted scripts directory containing a single recorded
    file so the count is deterministic.

    Validates: Requirement 5.6 (structured line with both counts).
    """
    from apps.common.management.commands import check_schema_drift

    recorded_file = _write_sql(tmp_path / "2024_01_01_recorded.sql")
    # Record it in migration_history so the helper does not flag it
    # as stale and the success path is taken.
    with connection.cursor() as cur:
        cur.execute(
            "INSERT INTO migration_history (migration_name, applied_at, "
            "checksum, notes) VALUES (%s, %s, %s, %s)",
            [
                recorded_file.name,
                "2024-01-01T00:00:00+00:00",
                "deadbeef",
                "test fixture",
            ],
        )

    fake_commit = datetime.now(timezone.utc) - timedelta(days=30)
    monkeypatch.setattr(
        check_schema_drift,
        "MIGRATION_SCRIPTS_DIR",
        tmp_path,
    )
    monkeypatch.setattr(
        check_schema_drift,
        "_git_commit_timestamp",
        lambda path: fake_commit,
    )

    out = StringIO()
    try:
        call_command(
            "check_schema_drift",
            "--check-fk-indexes",
            "--check-migration-history-coverage",
            stdout=out,
        )
    except SystemExit as exc:
        pytest.fail(
            f"check_schema_drift exited unexpectedly with both flags "
            f"(code={exc.code}). Output:\n{out.getvalue()}"
        )

    text = out.getvalue()
    assert "OK: schema-drift=" in text, (
        f"Expected structured OK line; got:\n{text}"
    )
    # FK-index helper short-circuits on SQLite with ``disabled``.
    assert "fk-indexes=disabled" in text
    # Migration-history helper found the bootstrap table and inspected
    # the single fixture script — count is 1 (the ``_rollback.sql``
    # filter and subdir exclusion are exercised by other tests).
    assert "migration-history=1" in text, (
        f"Expected migration-history=1 (one inspected script); got:\n{text}"
    )
    # Historical line must NOT appear on the structured path.
    assert "No schema drift. Verified" not in text


# ---------------------------------------------------------------------------
# 4. SQLite skip path — fk-indexes=disabled when the flag IS passed.
# ---------------------------------------------------------------------------


def test_fk_indexes_skipped_on_sqlite_emits_disabled_token():
    """When ``--check-fk-indexes`` is passed on SQLite the helper
    short-circuits with the Postgres-only skip message AND the
    structured ``OK:`` line carries ``fk-indexes=disabled``.

    The ``disabled`` token is intentionally identical to the
    flag-omitted case: from a CI log parser's perspective the cause is
    irrelevant — both mean "no FK-index verification was performed on
    this run". Operators reading the human-readable output still see
    the explicit skip message above the OK line.

    Validates: Requirement 5.6 (disabled token covers both omission and
    short-circuit).
    """
    if connection.vendor == "postgresql":
        pytest.skip(
            "SQLite skip path is exercised on the SQLite test settings; "
            "current backend is postgresql."
        )

    out = StringIO()
    try:
        call_command(
            "check_schema_drift",
            "--check-fk-indexes",
            stdout=out,
        )
    except SystemExit as exc:
        pytest.fail(
            f"check_schema_drift exited unexpectedly on SQLite "
            f"(code={exc.code}). Output:\n{out.getvalue()}"
        )

    text = out.getvalue()
    # Skip message confirms the helper short-circuited rather than
    # silently emitting ``disabled`` for some other reason.
    assert "--check-fk-indexes skipped" in text
    assert "Postgres-only" in text
    # Structured OK line carries the canonical disabled token.
    assert "fk-indexes=disabled" in text, (
        f"Expected fk-indexes=disabled after SQLite short-circuit; "
        f"got:\n{text}"
    )
    assert "OK: schema-drift=" in text


# ---------------------------------------------------------------------------
# Bonus: structured-line format is exact (no extra punctuation, fixed order).
# ---------------------------------------------------------------------------


def test_structured_ok_line_format_is_exact():
    """The structured success line matches ``OK: schema-drift=<n>
    fk-indexes=<m> migration-history=<k>`` exactly — single space
    separators, no trailing punctuation, fields in the canonical
    order.

    Locking the exact shape protects CI log parsers and runbook greps
    from drift in either direction (someone adding extra prose or
    re-ordering fields).

    Validates: Requirement 5.6 (canonical shape).
    """
    import re

    out = StringIO()
    call_command(
        "check_schema_drift",
        "--check-fk-indexes",
        stdout=out,
    )

    text = out.getvalue()
    # Match the line shape: any non-negative int OR the literal
    # "disabled" for each of the three slots, fields in fixed order,
    # single-space separators, end of line.
    pattern = re.compile(
        r"^OK: schema-drift=(\d+) fk-indexes=(\d+|disabled) "
        r"migration-history=(\d+|disabled)$",
        re.MULTILINE,
    )
    match = pattern.search(text)
    assert match is not None, (
        f"Structured OK line did not match canonical shape. Output:\n{text}"
    )
