"""Tests for the apply_sql_migrations management command.

Verifies:
- Refuses to run when the migration_history extend migration has not yet
  been applied (missing ``checksum`` column).
- Pending migrations are applied in filename order and recorded in
  ``migration_history`` with ``migration_name`` + sha256 ``checksum``.
- Already-applied migrations are skipped on re-run via
  ``ON CONFLICT (migration_name) DO NOTHING``.
- Failure in one migration raises CommandError; earlier successes kept.
- ``--dry-run`` lists pending migrations without applying them.
- Subdirectories under the migrations directory (``applied/``, ``archive/``,
  ``migrations/``) are not recursed into.

These tests cover the Component 2 refactor from
``.kiro/specs/production-schema-reconciliation/`` (task 1.2): the command
now writes to ``migration_history`` instead of the retired
``applied_sql_migrations`` table.
"""
from __future__ import annotations

import hashlib
from io import StringIO
from pathlib import Path

import pytest
from django.core.management import call_command
from django.core.management.base import CommandError
from django.db import connection


# DDL used by the fixtures to build a ``migration_history`` table that
# matches the post-extend shape (``checksum`` and ``notes`` columns +
# unique index on ``migration_name``). On Postgres this mirrors what
# ``2026_05_22_migration_history_extend.sql`` produces; on SQLite it
# uses equivalent column types so the same test suite runs under both
# vendors.

_PG_EXTENDED_DDL = """
CREATE TABLE migration_history (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    migration_name TEXT NOT NULL,
    applied_at TIMESTAMPTZ NULL,
    checksum TEXT NULL,
    notes TEXT NULL
);
CREATE UNIQUE INDEX uq_migration_history_migration_name
    ON migration_history (migration_name);
"""

_SQLITE_EXTENDED_DDL = """
CREATE TABLE migration_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    migration_name TEXT NOT NULL,
    applied_at TEXT NULL,
    checksum TEXT NULL,
    notes TEXT NULL
);
CREATE UNIQUE INDEX uq_migration_history_migration_name
    ON migration_history (migration_name);
"""

_PG_LEGACY_DDL = """
CREATE TABLE migration_history (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    migration_name TEXT NOT NULL,
    applied_at TIMESTAMPTZ NULL
);
"""

_SQLITE_LEGACY_DDL = """
CREATE TABLE migration_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    migration_name TEXT NOT NULL,
    applied_at TEXT NULL
);
"""


def _drop_migration_history() -> None:
    with connection.cursor() as cur:
        cur.execute("DROP INDEX IF EXISTS uq_migration_history_migration_name")
        cur.execute("DROP TABLE IF EXISTS migration_history")


def _create_extended_migration_history() -> None:
    ddl = _SQLITE_EXTENDED_DDL if connection.vendor == "sqlite" else _PG_EXTENDED_DDL
    with connection.cursor() as cur:
        for statement in [s.strip() for s in ddl.split(";") if s.strip()]:
            cur.execute(statement)


def _create_legacy_migration_history() -> None:
    """Build the pre-extend ``migration_history`` shape (no ``checksum``)."""
    ddl = _SQLITE_LEGACY_DDL if connection.vendor == "sqlite" else _PG_LEGACY_DDL
    with connection.cursor() as cur:
        for statement in [s.strip() for s in ddl.split(";") if s.strip()]:
            cur.execute(statement)


@pytest.fixture
def fresh_migration_history():
    """Provide an isolated ``migration_history`` table with the extended shape.

    Drops any pre-existing copy before and after each test so state cannot
    leak between cases. The table is created with ``checksum`` and
    ``notes`` columns and the supporting unique index, matching what
    ``2026_05_22_migration_history_extend.sql`` produces on production.
    """
    _drop_migration_history()
    _create_extended_migration_history()
    yield
    _drop_migration_history()


@pytest.fixture
def legacy_migration_history():
    """Provide a pre-extend ``migration_history`` table (no ``checksum``).

    Used only by the guard-clause test that verifies the command refuses
    to run when the extend migration has not yet been applied.
    """
    _drop_migration_history()
    _create_legacy_migration_history()
    yield
    _drop_migration_history()


@pytest.fixture
def migrations_dir(tmp_path):
    d = tmp_path / "scripts"
    d.mkdir()
    return d


def _write(path: Path, sql: str) -> None:
    path.write_text(sql)


def _table_exists(name: str) -> bool:
    if connection.vendor == "postgresql":
        with connection.cursor() as cur:
            cur.execute("SELECT to_regclass(%s)", [name])
            return cur.fetchone()[0] is not None
    return name in connection.introspection.table_names()


@pytest.mark.django_db
def test_refuses_to_run_when_migration_history_not_extended(
    legacy_migration_history, migrations_dir
):
    """Command bails with a clear message if ``checksum`` column is absent."""
    _write(
        migrations_dir / "0001_anything.sql",
        "CREATE TABLE IF NOT EXISTS _aux_smoke_guard (id INT PRIMARY KEY);",
    )

    with pytest.raises(CommandError) as exc:
        call_command(
            "apply_sql_migrations",
            "--migrations-dir",
            str(migrations_dir),
            stdout=StringIO(),
        )
    assert "MIGRATION_HISTORY_NOT_EXTENDED" in str(exc.value)
    # And no row was inserted because the command refused early.
    with connection.cursor() as cur:
        cur.execute("SELECT COUNT(*) FROM migration_history")
        assert cur.fetchone()[0] == 0


@pytest.mark.django_db
def test_empty_dir_is_a_no_op(fresh_migration_history, migrations_dir):
    out = StringIO()
    call_command(
        "apply_sql_migrations", "--migrations-dir", str(migrations_dir), stdout=out
    )
    assert "No migrations found" in out.getvalue()


@pytest.mark.django_db
def test_applies_pending_and_records_to_migration_history(
    fresh_migration_history, migrations_dir
):
    _write(
        migrations_dir / "0001_add_aux_table.sql",
        "CREATE TABLE IF NOT EXISTS _aux_smoke_a (id INT PRIMARY KEY);",
    )
    _write(
        migrations_dir / "0002_add_another.sql",
        "CREATE TABLE IF NOT EXISTS _aux_smoke_b (id INT PRIMARY KEY);",
    )

    out = StringIO()
    call_command(
        "apply_sql_migrations", "--migrations-dir", str(migrations_dir), stdout=out
    )

    text = out.getvalue()
    assert "Pending migrations: 2/2" in text
    assert "0001_add_aux_table.sql" in text
    assert "0002_add_another.sql" in text

    with connection.cursor() as cur:
        cur.execute(
            "SELECT migration_name FROM migration_history ORDER BY migration_name"
        )
        rows = [r[0] for r in cur.fetchall()]
        assert rows == ["0001_add_aux_table.sql", "0002_add_another.sql"]

        assert _table_exists("_aux_smoke_a")
        assert _table_exists("_aux_smoke_b")

    # Cleanup
    with connection.cursor() as cur:
        cur.execute("DROP TABLE IF EXISTS _aux_smoke_a")
        cur.execute("DROP TABLE IF EXISTS _aux_smoke_b")


@pytest.mark.django_db
def test_rerun_skips_applied(fresh_migration_history, migrations_dir):
    _write(
        migrations_dir / "0001_idempotent.sql",
        "CREATE TABLE IF NOT EXISTS _aux_smoke_idem (id INT PRIMARY KEY);",
    )

    call_command(
        "apply_sql_migrations",
        "--migrations-dir",
        str(migrations_dir),
        stdout=StringIO(),
    )
    out = StringIO()
    call_command(
        "apply_sql_migrations", "--migrations-dir", str(migrations_dir), stdout=out
    )

    assert "already applied" in out.getvalue()

    with connection.cursor() as cur:
        cur.execute("SELECT COUNT(*) FROM migration_history")
        assert cur.fetchone()[0] == 1
        cur.execute("DROP TABLE IF EXISTS _aux_smoke_idem")


@pytest.mark.django_db
def test_stores_checksum(fresh_migration_history, migrations_dir):
    sql = "CREATE TABLE IF NOT EXISTS _aux_smoke_chk (id INT PRIMARY KEY);"
    _write(migrations_dir / "0001_chk.sql", sql)
    expected = hashlib.sha256(sql.encode()).hexdigest()

    call_command(
        "apply_sql_migrations",
        "--migrations-dir",
        str(migrations_dir),
        stdout=StringIO(),
    )

    with connection.cursor() as cur:
        cur.execute(
            "SELECT checksum FROM migration_history WHERE migration_name = %s",
            ["0001_chk.sql"],
        )
        assert cur.fetchone()[0] == expected
        cur.execute("DROP TABLE IF EXISTS _aux_smoke_chk")


@pytest.mark.django_db
def test_dry_run_does_not_apply(fresh_migration_history, migrations_dir):
    _write(
        migrations_dir / "0001_unapplied.sql",
        "CREATE TABLE IF NOT EXISTS _aux_smoke_dry (id INT PRIMARY KEY);",
    )

    out = StringIO()
    call_command(
        "apply_sql_migrations",
        "--migrations-dir",
        str(migrations_dir),
        "--dry-run",
        stdout=out,
    )

    assert "[dry-run]" in out.getvalue()
    assert not _table_exists("_aux_smoke_dry")
    with connection.cursor() as cur:
        cur.execute("SELECT COUNT(*) FROM migration_history")
        assert cur.fetchone()[0] == 0


@pytest.mark.django_db
def test_failure_raises_and_earlier_success_kept(
    fresh_migration_history, migrations_dir
):
    _write(
        migrations_dir / "0001_ok.sql",
        "CREATE TABLE IF NOT EXISTS _aux_smoke_ok (id INT PRIMARY KEY);",
    )
    _write(
        migrations_dir / "0002_bad.sql",
        "THIS IS NOT VALID SQL;",
    )

    with pytest.raises(CommandError) as exc:
        call_command(
            "apply_sql_migrations",
            "--migrations-dir",
            str(migrations_dir),
            stdout=StringIO(),
        )
    assert "0002_bad.sql" in str(exc.value)

    # The first (successful) migration MUST still be recorded so a retry
    # does not double-apply it.
    with connection.cursor() as cur:
        cur.execute(
            "SELECT migration_name FROM migration_history ORDER BY migration_name"
        )
        rows = [r[0] for r in cur.fetchall()]
        assert "0001_ok.sql" in rows
        assert "0002_bad.sql" not in rows
        cur.execute("DROP TABLE IF EXISTS _aux_smoke_ok")


@pytest.mark.django_db
def test_non_sql_files_are_ignored(fresh_migration_history, migrations_dir):
    _write(migrations_dir / "README.md", "# nope")
    _write(migrations_dir / "helpers.py", "x = 1")
    _write(
        migrations_dir / "0001_real.sql",
        "CREATE TABLE IF NOT EXISTS _aux_smoke_filter (id INT PRIMARY KEY);",
    )

    call_command(
        "apply_sql_migrations",
        "--migrations-dir",
        str(migrations_dir),
        stdout=StringIO(),
    )

    with connection.cursor() as cur:
        cur.execute("SELECT migration_name FROM migration_history")
        rows = [r[0] for r in cur.fetchall()]
        assert rows == ["0001_real.sql"]
        cur.execute("DROP TABLE IF EXISTS _aux_smoke_filter")


@pytest.mark.django_db
def test_excluded_subdirectories_are_not_recursed(
    fresh_migration_history, migrations_dir
):
    """Files under ``applied/``, ``archive/``, and ``migrations/`` are skipped.

    The command iterates only the top level of the migrations directory,
    so any ``.sql`` file placed in one of these excluded subdirectories
    must not be applied or recorded.
    """
    # Top-level file: should be applied.
    _write(
        migrations_dir / "0001_top_level.sql",
        "CREATE TABLE IF NOT EXISTS _aux_smoke_top (id INT PRIMARY KEY);",
    )

    # Files inside excluded subdirectories: must be skipped.
    for sub in ("applied", "archive", "migrations"):
        sub_dir = migrations_dir / sub
        sub_dir.mkdir()
        _write(
            sub_dir / "0099_should_not_run.sql",
            "CREATE TABLE IF NOT EXISTS _aux_smoke_excluded (id INT PRIMARY KEY);",
        )

    call_command(
        "apply_sql_migrations",
        "--migrations-dir",
        str(migrations_dir),
        stdout=StringIO(),
    )

    with connection.cursor() as cur:
        cur.execute("SELECT migration_name FROM migration_history")
        rows = [r[0] for r in cur.fetchall()]
        assert rows == ["0001_top_level.sql"]
        # The excluded subdir SQL must not have run.
        assert not _table_exists("_aux_smoke_excluded")
        cur.execute("DROP TABLE IF EXISTS _aux_smoke_top")


# ---------------------------------------------------------------------------
# Task 1.3 — CREATE INDEX CONCURRENTLY split-phase handling
# ---------------------------------------------------------------------------
#
# These tests cover:
# * Detection of ``CREATE INDEX CONCURRENTLY`` is case-insensitive and
#   ignores ``--`` line comments — a documentation comment must NOT
#   trigger split-phase handling.
# * On Postgres only: a file containing ``CREATE INDEX CONCURRENTLY``
#   runs in autocommit mode for the index build, and the
#   ``migration_history`` row is written separately afterwards.
# * On error during the autocommit phase, no ``migration_history`` row
#   is written and the command exits non-zero.
#
# Detection is exercised at the helper level so the test suite still
# passes on SQLite (which has no ``CONCURRENTLY``). The behavioural
# Postgres-only tests are skipped on SQLite via
# ``connection.vendor == "postgresql"`` gates, matching the existing
# ``test_payment_migration_indexes`` style.

from apps.common.management.commands.apply_sql_migrations import (  # noqa: E402
    _extract_concurrently_index_names,
    _has_concurrently,
)


class TestConcurrentlyDetection:
    """Detection helpers must be case-insensitive and comment-aware."""

    def test_detects_lowercase_concurrently(self):
        sql = "create index concurrently idx_foo on foo(bar);"
        assert _has_concurrently(sql) is True

    def test_detects_mixed_case_concurrently(self):
        sql = "Create Index Concurrently idx_foo ON foo(bar);"
        assert _has_concurrently(sql) is True

    def test_detects_extra_whitespace_concurrently(self):
        sql = "CREATE   INDEX\n  CONCURRENTLY  idx_foo ON foo(bar);"
        assert _has_concurrently(sql) is True

    def test_detects_if_not_exists_variant(self):
        sql = (
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_foo ON foo(bar);\n"
        )
        assert _has_concurrently(sql) is True

    def test_ignores_concurrently_inside_line_comment(self):
        """A doc comment must NOT trigger split-phase handling."""
        sql = (
            "-- CREATE INDEX CONCURRENTLY idx_foo ON foo(bar);\n"
            "CREATE TABLE quux (id INT PRIMARY KEY);\n"
        )
        assert _has_concurrently(sql) is False

    def test_ignores_concurrently_after_inline_comment_marker(self):
        sql = "SELECT 1; -- CREATE INDEX CONCURRENTLY idx_foo ON foo(bar);\n"
        assert _has_concurrently(sql) is False

    def test_returns_false_for_plain_create_index(self):
        sql = "CREATE INDEX idx_foo ON foo(bar);"
        assert _has_concurrently(sql) is False

    def test_extracts_unquoted_index_name(self):
        sql = "CREATE INDEX CONCURRENTLY idx_foo ON foo(bar);"
        assert _extract_concurrently_index_names(sql) == ["idx_foo"]

    def test_extracts_if_not_exists_index_name(self):
        sql = "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_foo ON foo(bar);"
        assert _extract_concurrently_index_names(sql) == ["idx_foo"]

    def test_extracts_quoted_index_name(self):
        sql = 'CREATE INDEX CONCURRENTLY "idx Foo Bar" ON foo(bar);'
        assert _extract_concurrently_index_names(sql) == ["idx Foo Bar"]

    def test_extracts_multiple_index_names(self):
        sql = (
            "CREATE INDEX CONCURRENTLY idx_a ON foo(a);\n"
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_b ON foo(b);\n"
        )
        assert _extract_concurrently_index_names(sql) == ["idx_a", "idx_b"]

    def test_ignores_index_names_in_comments(self):
        sql = (
            "-- CREATE INDEX CONCURRENTLY idx_in_comment ON foo(bar);\n"
            "CREATE INDEX CONCURRENTLY idx_real ON foo(bar);\n"
        )
        assert _extract_concurrently_index_names(sql) == ["idx_real"]


@pytest.mark.django_db(transaction=True)
@pytest.mark.skipif(
    connection.vendor != "postgresql",
    reason="CREATE INDEX CONCURRENTLY is Postgres-only",
)
def test_concurrently_index_runs_in_autocommit_and_records_history(
    fresh_migration_history, migrations_dir
):
    """A CONCURRENTLY file must run in autocommit and record history.

    Verifies:
    * The index is actually built (queryable via ``pg_index``).
    * A ``migration_history`` row is written for the file.
    * The connection's autocommit state is restored after the run.
    """
    # Setup target table (in its own statement so the migration file
    # only contains the CONCURRENTLY index build).
    with connection.cursor() as cur:
        cur.execute(
            "CREATE TABLE IF NOT EXISTS _aux_concurrently_target "
            "(id INT PRIMARY KEY, name TEXT)"
        )

    autocommit_before = connection.get_autocommit()
    _write(
        migrations_dir / "0001_concurrently.sql",
        "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
        "idx_aux_concurrently_target_name "
        "ON _aux_concurrently_target(name);",
    )

    out = StringIO()
    call_command(
        "apply_sql_migrations",
        "--migrations-dir",
        str(migrations_dir),
        stdout=out,
    )

    # Connection autocommit must be restored to what we found.
    assert connection.get_autocommit() == autocommit_before

    with connection.cursor() as cur:
        # The index must exist and be valid.
        cur.execute(
            "SELECT i.indisvalid FROM pg_index i "
            "JOIN pg_class c ON c.oid = i.indexrelid "
            "WHERE c.relname = %s",
            ["idx_aux_concurrently_target_name"],
        )
        row = cur.fetchone()
        assert row is not None and row[0] is True

        # And ``migration_history`` records the file.
        cur.execute(
            "SELECT migration_name FROM migration_history "
            "WHERE migration_name = %s",
            ["0001_concurrently.sql"],
        )
        assert cur.fetchone() is not None

        cur.execute(
            "DROP INDEX IF EXISTS idx_aux_concurrently_target_name"
        )
        cur.execute("DROP TABLE IF EXISTS _aux_concurrently_target")


@pytest.mark.django_db(transaction=True)
@pytest.mark.skipif(
    connection.vendor != "postgresql",
    reason="CREATE INDEX CONCURRENTLY is Postgres-only",
)
def test_concurrently_phase_error_skips_history_and_exits_nonzero(
    fresh_migration_history, migrations_dir
):
    """An error during the autocommit phase must NOT record history."""
    # Migration file references a table that does not exist, so the
    # CONCURRENTLY build will fail with ``relation does not exist``.
    _write(
        migrations_dir / "0001_concurrently_bad.sql",
        "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
        "idx_nonexistent_table_col "
        "ON _table_that_does_not_exist(col);",
    )

    autocommit_before = connection.get_autocommit()

    with pytest.raises(CommandError) as exc:
        call_command(
            "apply_sql_migrations",
            "--migrations-dir",
            str(migrations_dir),
            stdout=StringIO(),
        )
    assert "0001_concurrently_bad.sql" in str(exc.value)

    # Autocommit state must still be restored.
    assert connection.get_autocommit() == autocommit_before

    # No ``migration_history`` row must have been written.
    with connection.cursor() as cur:
        cur.execute(
            "SELECT COUNT(*) FROM migration_history "
            "WHERE migration_name = %s",
            ["0001_concurrently_bad.sql"],
        )
        assert cur.fetchone()[0] == 0


# ---------------------------------------------------------------------------
# Top-level filename exclusion (rollback siblings + design-deferred files)
# ---------------------------------------------------------------------------
#
# Container startup (Koyeb) runs ``python manage.py apply_sql_migrations``
# before serving traffic. Without these exclusions the lexical sweep
# would try to apply every ``*_rollback.sql`` sibling and the
# documented-deferred files (``00_full_schema.sql``,
# ``legacy_columns_drop_2026_08_15.sql``), and the additive-only lint
# from Task 1.5 would reject them — crashlooping the container.
#
# These tests pin the exclusion list so a future refactor cannot
# regress that boot path.


@pytest.mark.django_db
def test_rollback_sibling_files_are_skipped(
    fresh_migration_history, migrations_dir
):
    """``*_rollback.sql`` files must not be picked up by the lexical sweep.

    Per Requirement 9.5 of the production-schema-reconciliation spec,
    rollback files are applied manually by the operator — never by
    ``apply_sql_migrations``. Without this exclusion a forward script
    paired with its sibling rollback would crash the container at
    startup because the additive lint flags the rollback's
    ``DROP COLUMN`` / ``DROP INDEX`` statements as non-additive.
    """
    _write(
        migrations_dir / "0001_forward.sql",
        "CREATE TABLE IF NOT EXISTS _aux_smoke_rb (id INT PRIMARY KEY);",
    )
    _write(
        migrations_dir / "0001_forward_rollback.sql",
        "DROP TABLE IF EXISTS _aux_smoke_rb;",
    )

    out = StringIO()
    call_command(
        "apply_sql_migrations",
        "--migrations-dir",
        str(migrations_dir),
        stdout=out,
    )

    text = out.getvalue()
    # Forward must apply.
    assert "0001_forward.sql" in text
    # Rollback must NOT be mentioned in the apply output.
    assert "0001_forward_rollback.sql" not in text

    with connection.cursor() as cur:
        cur.execute(
            "SELECT migration_name FROM migration_history "
            "WHERE migration_name IN (%s, %s)",
            ["0001_forward.sql", "0001_forward_rollback.sql"],
        )
        rows = {row[0] for row in cur.fetchall()}
        assert "0001_forward.sql" in rows
        assert "0001_forward_rollback.sql" not in rows
        cur.execute("DROP TABLE IF EXISTS _aux_smoke_rb")


@pytest.mark.django_db
def test_excluded_top_level_filenames_are_skipped(
    fresh_migration_history, migrations_dir
):
    """``00_full_schema.sql`` and ``legacy_columns_drop_2026_08_15.sql``
    must be skipped per design.md Component 3.

    These two filenames are documented exclusions: the first is a
    generated documentation snapshot, the second is a deliberately
    deferred future cleanup. Auto-applying either at container
    startup would either re-execute the entire schema or attempt a
    non-additive cleanup ahead of schedule.
    """
    # Both excluded files would crash the lint (or the connection)
    # if they ever ran. Their bodies are intentionally syntactically
    # valid additive SQL so the only thing keeping the test green is
    # the filename-based exclusion.
    _write(
        migrations_dir / "00_full_schema.sql",
        "CREATE TABLE IF NOT EXISTS _aux_smoke_skip_a (id INT PRIMARY KEY);",
    )
    _write(
        migrations_dir / "legacy_columns_drop_2026_08_15.sql",
        "CREATE TABLE IF NOT EXISTS _aux_smoke_skip_b (id INT PRIMARY KEY);",
    )
    _write(
        migrations_dir / "0001_real_target.sql",
        "CREATE TABLE IF NOT EXISTS _aux_smoke_real (id INT PRIMARY KEY);",
    )

    call_command(
        "apply_sql_migrations",
        "--migrations-dir",
        str(migrations_dir),
        stdout=StringIO(),
    )

    with connection.cursor() as cur:
        cur.execute("SELECT migration_name FROM migration_history")
        rows = {row[0] for row in cur.fetchall()}
        assert "0001_real_target.sql" in rows
        assert "00_full_schema.sql" not in rows
        assert "legacy_columns_drop_2026_08_15.sql" not in rows
        cur.execute("DROP TABLE IF EXISTS _aux_smoke_skip_a")
        cur.execute("DROP TABLE IF EXISTS _aux_smoke_skip_b")
        cur.execute("DROP TABLE IF EXISTS _aux_smoke_real")


@pytest.mark.django_db
def test_legacy_payment_hardening_rollback_is_skipped(
    fresh_migration_history, migrations_dir
):
    """The pre-existing ``payment_hardening_indexes_rollback.sql`` shipped
    in the checkout must also be skipped — it predates this spec and
    has no forward sibling at top level, but matches the
    ``*_rollback.sql`` convention so the suffix-based exclusion still
    catches it. This test pins that behaviour because the file is
    actually present in production checkouts.
    """
    _write(
        migrations_dir / "payment_hardening_indexes_rollback.sql",
        "DROP INDEX IF EXISTS uq_payments_receipt_number;",
    )
    _write(
        migrations_dir / "0001_unrelated_forward.sql",
        "CREATE TABLE IF NOT EXISTS _aux_smoke_unrel (id INT PRIMARY KEY);",
    )

    call_command(
        "apply_sql_migrations",
        "--migrations-dir",
        str(migrations_dir),
        stdout=StringIO(),
    )

    with connection.cursor() as cur:
        cur.execute("SELECT migration_name FROM migration_history")
        rows = {row[0] for row in cur.fetchall()}
        assert "0001_unrelated_forward.sql" in rows
        assert "payment_hardening_indexes_rollback.sql" not in rows
        cur.execute("DROP TABLE IF EXISTS _aux_smoke_unrel")
