import { defineConfig } from 'vitest/config';
import path from 'path';

export default defineConfig({
  test: {
    globals: true,
    environment: 'jsdom',
    include: ['tests/**/*.{test,spec,property}.{ts,tsx}'],
    exclude: [
      'tests/e2e/**',
      'tests/unit/api/**',
      'tests/integration/applicationsCatalogValidation.integration.test.ts',
      'tests/integration/schemaVerification.test.ts',
      'tests/integration/email-check.integration.test.ts',
      'tests/integration/mime-types.integration.test.ts',
      'tests/unit/auth.test.ts',
      'tests/unit/applicationQueriesLocationFields.test.ts',
      'tests/unit/applicationsCreateValidation.test.ts',
      'tests/unit/auth-middleware.test.ts',
      'tests/unit/auth-permissions.test.ts',
      'tests/unit/fileValidator.test.ts',
      'tests/unit/notificationPolicyEnforcement.test.ts',
      'tests/unit/optimized-auth-routes.test.tsx',
      'tests/unit/profileApiSchemaDrift.test.ts',
      'tests/unit/profileSchemaCanonicalCountry.test.ts',
      'tests/unit/registerBodySchema.test.ts',
      'tests/unit/transactionWrapping.test.ts',
      'tests/unit/urlValidator.test.ts',
      'tests/unit/wizardValidation.test.ts',
      'tests/unit/audit-remediation-code-structure.test.ts',
      'tests/unit/auditTrailCompleteness.test.ts',
      'tests/unit/doubleSubmit.test.ts',
      'tests/unit/generateIdempotencyKey.test.ts',
      'tests/unit/api-auth-*.test.ts',
      'tests/unit/contracts/actionAlignment.test.ts',
      'tests/property/adminRbac.property.test.ts',
      'tests/property/admin-users-registration-bugfix-*.test.ts',
      'tests/property/audit-remediation-*.test.ts',
      'tests/property/auditLogger.property.test.ts',
      'tests/property/auth-api.property.test.ts',
      'tests/property/authCookies.property.test.ts',
      'tests/property/batchQuery.property.test.ts',
      'tests/property/cookies.property.test.ts',
      'tests/property/cors.property.ts',
      'tests/property/csrf.property.test.ts',
      'tests/property/db.property.test.ts',
      'tests/property/envValidator.property.test.ts',
      'tests/property/error-handling.property.test.ts',
      'tests/property/fileValidator.property.test.ts',
      'tests/property/jsonResponses.property.test.ts',
      'tests/property/jwt.property.test.ts',
      'tests/property/jwtDecoding.property.test.ts',
      'tests/property/password.property.test.ts',
      'tests/property/rbac.property.test.ts',
      'tests/property/rbacDeterminism.property.test.ts',
      'tests/property/sensitiveDataSanitization.property.test.ts',
      'tests/property/*Analyzer.property.test.ts',
      'tests/property/*Auditor.property.test.ts',
      'tests/property/*Checker.property.test.ts',
      'tests/property/*Detector.property.test.ts',
      'tests/property/*Scanner.property.test.ts',
      'tests/property/*Verifier.property.test.ts',
      'tests/property/consolidation-sanitize.test.ts',
      'tests/property/urlValidator.property.test.ts',
      'tests/property/validation.property.test.ts',
      'tests/property/workflowTransitions.property.test.ts',
      'tests/property/admin-system-health-fixes/**',
      'tests/property/api-hardening/**',
      'tests/property/contractAuditor.property.test.ts',
      'tests/property/credentialScan.property.test.ts',
      'tests/property/evidenceGenerator.property.test.ts',
      'tests/property/idempotencyChecker.property.test.ts',
      'tests/property/idempotencyDedup.property.test.ts',
      'tests/property/notificationAuditor.property.test.ts',
      'tests/property/vercel-production-fixes/error-response.property.test.ts',
      'tests/property/production-readiness-audit/**',
      'tests/property/production-site-fixes/**',
      'tests/property/rateLimiting.property.test.ts',
      'tests/property/schemaComparator.property.test.ts',
      'tests/property/sseAuditor.property.test.ts',
      'tests/property/supabase-complete-removal/**',
      'tests/routes/adminRouteCoverage.test.ts',
      'tests/unit/adminReportTemplatesLegacyEndpointGuard.test.ts',
      'tests/unit/adminRoleSupport.test.ts',
      'tests/unit/commentedCodeScanner.test.ts',
      'tests/unit/featureFlagScanner.test.ts',
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
    },
    testTimeout: 30000,
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      '@neondatabase/serverless': path.resolve(__dirname, './node_modules/@neondatabase/serverless'),
    },
  },
});
