/**
 * MIHAS-KATC PDF Theme — Public Barrel
 *
 * Import everything design-system-related through this file:
 *
 *   import { colors, space, textStyles, logos } from '@/lib/pdf/theme'
 *
 * Never import directly from the sub-files in production code — keeps
 * refactors localized to this barrel.
 */

export { colors, semantic } from './colors'
export type { SemanticColor } from './colors'

export {
  spacing,
  space,
  pageDimensions,
  radius,
  borderWidth,
} from './spacing'

export {
  FONT_FAMILY,
  registerPdfFonts,
  typeScale,
  textStyles,
  __resetFontRegistration,
} from './typography'
export type { TypeScaleKey, TextStyleKey } from './typography'

/**
 * Institution logo asset paths. All files live in /public/images/logos/ and
 * are served same-origin. @react-pdf fetches them at render time via the
 * <Image src={...}> component.
 *
 * The MIHAS and KATC logos exist as both .png and .webp; @react-pdf requires
 * PNG/JPEG (no WebP support as of v4.x), so we use .png variants here.
 */
export const logos = {
  mihas: '/images/logos/mihas-logo.png',
  katc: '/images/logos/katc-logo.png',
  mihasFull: '/images/logos/mukuba institute of health and applied sciences logo.png',
  katcFull: '/images/logos/kalulushi training centre logo.png',
  beanola: '/images/logos/beanolalogo.png',
} as const

/**
 * Shape of an institution record used by the PDF preview layer.
 */
export interface Institution {
  code: string
  shortName: string
  fullName: string
  logoMark: string
  logoFull: string
  address: string
  detailedAddress: string
  phone: string
  email: string
  website: string
}

/**
 * Beanola-generic preview profile. Used by the dev/draft PDF preview path
 * (`@/lib/pdf`) when the institution is unknown. Official documents are
 * generated by the backend tenant-aware generator and never reach this
 * fallback — so an unknown institution here yields a neutral Beanola
 * shared-platform preview rather than silently inheriting a school identity.
 */
export const BEANOLA_GENERIC: Institution = {
  code: 'BEANOLA',
  shortName: 'Beanola',
  fullName: 'Beanola Admissions',
  logoMark: logos.beanola,
  logoFull: logos.beanola,
  address: '',
  detailedAddress: '',
  phone: '',
  email: '',
  website: 'www.beanola.com',
}

/**
 * Institution registry — canonical names + logo mapping. Document components
 * call `getInstitution(code)` to resolve any short code into the correct
 * display name and logo path. MIHAS and KATC are tenant data, not platform
 * defaults — they live here only as known preview tenants.
 */
export const institutions = {
  MIHAS: {
    code: 'MIHAS',
    shortName: 'MIHAS',
    fullName: 'Mukuba Institute of Health and Applied Sciences',
    logoMark: logos.mihas,
    logoFull: logos.mihasFull,
    // Short form used in the PDF header — narrow column, must fit on one line.
    address: 'Plot 3375 President Avenue, P.O. Box 260218, Kalulushi, Zambia',
    // Full descriptive address with landmarks — suitable for letters, emails,
    // and the contact page where the extra detail helps applicants find us.
    detailedAddress:
      'Plot 3375 Off President Avenue, Kalulushi — next to the Civic Centre, opposite Kalulushi General Hospital',
    phone: '+260 961 515151',
    email: 'info@mihas.edu.zm',
    website: 'www.mihas.edu.zm',
  },
  KATC: {
    code: 'KATC',
    shortName: 'KATC',
    fullName: 'Kalulushi Training Centre',
    logoMark: logos.katc,
    logoFull: logos.katcFull,
    address: 'Plot 110206 Dag Hammarskjöld Street, P.O. Box 23597, Kalulushi, Zambia',
    detailedAddress:
      'Plot 110206 Dag Hammarskjöld Street, P.O. Box 23597, Kalulushi, Zambia',
    phone: '+260 966 992299',
    email: 'info@katc.edu.zm',
    website: 'www.katc.edu.zm',
  },
} satisfies Record<string, Institution>

export type InstitutionCode = keyof typeof institutions

/**
 * Resolve a short code or unknown string into an Institution record for the
 * dev/draft PDF preview layer.
 *
 * Behaviour:
 *   - null / undefined / empty string  → Beanola-generic preview profile
 *     (the shared platform default; no school is implied).
 *   - "MIHAS" / "KATC" (any case)      → the matching known preview tenant.
 *   - a known full name / alias        → the matching known preview tenant.
 *   - any other non-empty string       → logs a warning and returns the
 *     Beanola-generic profile. The warning surfaces a likely backend/frontend
 *     contract drift. This never silently renders a MIHAS identity.
 *
 * Official documents are backend-generated; this preview helper must never
 * present an unknown institution as MIHAS.
 */
export function getInstitution(code: string | null | undefined): Institution {
  if (!code) return BEANOLA_GENERIC
  const value = code.trim()
  if (!value) return BEANOLA_GENERIC

  // 1. Exact short-code match (case-insensitive): "MIHAS" / "KATC".
  const upper = value.toUpperCase()
  if (upper in institutions) return institutions[upper as InstitutionCode]

  // 2. Full-name / alias match. The backend stores `application.institution`
  //    as the full institution NAME (e.g. "Kalulushi Training Centre"), not
  //    the short code — so match known names/aliases here.
  const lower = value.toLowerCase()
  if (lower.includes('katc') || lower.includes('kalulushi')) return institutions.KATC
  if (lower.includes('mihas') || lower.includes('mukuba')) return institutions.MIHAS

  // 3. Unknown code — surface the drift and fall back to the Beanola-generic
  //    preview profile, never to a school identity.
  if (typeof console !== 'undefined' && typeof console.warn === 'function') {
    console.warn(
      `[pdf/theme] Unknown institution code "${code}" — using the Beanola-generic ` +
        `preview profile. Known preview tenants: ${Object.keys(institutions).join(', ')}. ` +
        'Official documents are backend-generated; this affects dev/draft preview only.',
    )
  }
  return BEANOLA_GENERIC
}
