"""Property-based tests for forward-only migration_history tracking.

# Feature: production-schema-reconciliation
# Property 6: Forward-Only Tracking
# Property 8: Idempotent Re-Apply

Validates that:
- The ``migration_history`` row count is monotonically non-decreasing
  across any sequence of ``apply_sql_migrations`` runs (Property 6).
  Forward-applied rows are never lost when subsequent runs see a
  different (or empty) pending set.
- Running ``apply_sql_migrations`` against the same migration set N
  times in succession produces the same ``migration_history`` state
  as a single run — the ``ON CONFLICT (migration_name) DO NOTHING``
  insert prevents duplicate rows from re-applying the same filename
  (Property 8).

These properties are exercised against the actual ``apply_sql_migrations``
management command so the test catches regressions in the real code path
(not a re-implementation). The command runs against the configured
Django database — which is SQLite by default in this repo's local test
suite, and Postgres on Neon when ``DATABASE_URL`` points there. Both
vendors are supported because the command's tracking-table SQL is
already vendor-aware (see ``_record_applied`` and ``_has_extended_migration_history``).

**Validates: Requirements 1.8, 4.5, 8.6**

Spec: ``.kiro/specs/production-schema-reconciliation/`` — Task 1.4.
"""
from __future__ import annotations

import os
import tempfile
from io import StringIO
from pathlib import Path

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.dev")
os.environ["TESTING"] = "1"

import django  # noqa: E402

django.setup()

import pytest  # noqa: E402
from django.core.management import call_command  # noqa: E402
from django.db import connection  # noqa: E402
from hypothesis import given, settings  # noqa: E402
from hypothesis import strategies as st  # noqa: E402


# ---------------------------------------------------------------------------
# Tracking-table fixtures
# ---------------------------------------------------------------------------
#
# These DDL strings mirror what ``2026_05_22_migration_history_extend.sql``
# produces on production. They are duplicated here (rather than imported
# from the unit test module) so the property test file stays self-contained
# and independent of the unit-test layout.

_PG_EXTENDED_DDL = """
CREATE TABLE migration_history (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    migration_name TEXT NOT NULL,
    applied_at TIMESTAMPTZ NULL,
    checksum TEXT NULL,
    notes TEXT NULL
);
CREATE UNIQUE INDEX uq_migration_history_migration_name
    ON migration_history (migration_name);
"""

_SQLITE_EXTENDED_DDL = """
CREATE TABLE migration_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    migration_name TEXT NOT NULL,
    applied_at TEXT NULL,
    checksum TEXT NULL,
    notes TEXT NULL
);
CREATE UNIQUE INDEX uq_migration_history_migration_name
    ON migration_history (migration_name);
"""


def _drop_migration_history() -> None:
    """Reset the tracking table between hypothesis examples."""
    with connection.cursor() as cur:
        cur.execute("DROP INDEX IF EXISTS uq_migration_history_migration_name")
        cur.execute("DROP TABLE IF EXISTS migration_history")


def _create_extended_migration_history() -> None:
    """Build the extended tracking shape (with ``checksum`` + ``notes``)."""
    ddl = _SQLITE_EXTENDED_DDL if connection.vendor == "sqlite" else _PG_EXTENDED_DDL
    with connection.cursor() as cur:
        for statement in [s.strip() for s in ddl.split(";") if s.strip()]:
            cur.execute(statement)


def _row_count() -> int:
    with connection.cursor() as cur:
        cur.execute("SELECT COUNT(*) FROM migration_history")
        return int(cur.fetchone()[0])


def _migration_names() -> list[str]:
    with connection.cursor() as cur:
        cur.execute(
            "SELECT migration_name FROM migration_history ORDER BY migration_name"
        )
        return [row[0] for row in cur.fetchall()]


# ---------------------------------------------------------------------------
# Strategies
# ---------------------------------------------------------------------------
#
# Filenames use a lowercase-ASCII + digit alphabet so they are
# filesystem-safe on every supported OS, and end in ``.sql`` so
# ``apply_sql_migrations`` actually picks them up. ``unique=True`` on
# the parent list keeps generators from accidentally producing the same
# file twice in a single example, which would change the on-disk
# semantics under us.

_filename_st = st.text(
    alphabet="abcdefghijklmnopqrstuvwxyz0123456789",
    min_size=3,
    max_size=12,
).map(lambda s: f"{s}.sql")


def _write_files(tmp_dir: Path, filenames: list[str]) -> None:
    """(Re-)populate ``tmp_dir`` with exactly the given filenames.

    Existing files are removed first so each step in a sequence presents
    a clean subset to ``apply_sql_migrations``. The body of every file
    is a single ``SELECT 1;`` statement — vendor-portable, side-effect
    free, and known to be picked up as a "successful migration" by the
    command's transactional path.
    """
    for child in list(tmp_dir.iterdir()):
        if child.is_file():
            child.unlink()
    for name in filenames:
        (tmp_dir / name).write_text("SELECT 1;")


def _run_apply() -> None:
    """Invoke ``apply_sql_migrations`` against the current connection.

    Output is captured but discarded — the property tests assert against
    database state, not stdout.
    """
    # ``--migrations-dir`` is set by the caller via the closure. We need
    # to pass it explicitly each time, so this helper takes a path.
    raise NotImplementedError("Use _apply_against(tmp_dir) instead")


def _apply_against(tmp_dir: Path) -> None:
    call_command(
        "apply_sql_migrations",
        "--migrations-dir",
        str(tmp_dir),
        stdout=StringIO(),
        stderr=StringIO(),
    )


# ---------------------------------------------------------------------------
# Property 6: Forward-Only Tracking
# ---------------------------------------------------------------------------


@pytest.mark.django_db(transaction=True)
@given(
    filenames=st.lists(_filename_st, min_size=1, max_size=8, unique=True),
    step_counts=st.lists(
        st.integers(min_value=0, max_value=8),
        min_size=1,
        max_size=6,
    ),
)
@settings(max_examples=20, deadline=2000)
def test_migration_history_row_count_is_monotonically_non_decreasing(
    filenames: list[str], step_counts: list[int]
) -> None:
    """Property 6: ``migration_history`` row count never decreases.

    For any sequence of ``apply_sql_migrations`` runs against the same
    database — even when later runs see a strictly smaller pending set
    (or no pending files at all) — the count of rows in
    ``migration_history`` SHALL be greater than or equal to the count
    after every previous run, AND the set of recorded ``migration_name``
    values SHALL be a strict superset of every previous set.

    No row SHALL ever appear twice for the same ``migration_name``.

    **Validates: Requirements 1.8, 4.5, 8.6**
    """
    _drop_migration_history()
    _create_extended_migration_history()
    try:
        with tempfile.TemporaryDirectory(prefix="kf-mig-") as tmp:
            tmp_dir = Path(tmp)
            sorted_files = sorted(filenames)
            previous_count = 0
            previous_names: set[str] = set()

            for raw_count in step_counts:
                # Each step presents a (possibly empty, possibly partial,
                # possibly full) subset of the filename pool to the command.
                # The dir is rewritten from scratch each time so a step
                # may present strictly fewer files than a previous step —
                # which is exactly the forward-only stress case.
                count = min(raw_count, len(sorted_files))
                _write_files(tmp_dir, sorted_files[:count])

                _apply_against(tmp_dir)

                current_count = _row_count()
                current_names_list = _migration_names()
                current_names = set(current_names_list)

                # Property 6 — primary assertion: monotonically non-decreasing.
                assert current_count >= previous_count, (
                    f"migration_history row count decreased from "
                    f"{previous_count} to {current_count}. "
                    f"previous_names={sorted(previous_names)}, "
                    f"current_names={sorted(current_names)}"
                )

                # Forward-only superset invariant: every previously
                # recorded name still appears.
                missing = previous_names - current_names
                assert not missing, (
                    f"Forward-only invariant violated. Names lost: "
                    f"{sorted(missing)}. previous_names="
                    f"{sorted(previous_names)}, current_names="
                    f"{sorted(current_names)}"
                )

                # Property 8 sub-condition: no duplicate rows for the
                # same migration_name. The unique index makes this a
                # database-level guarantee; we still assert it here so
                # a regression in the index would surface as a property
                # failure rather than an opaque IntegrityError.
                assert current_count == len(current_names), (
                    f"Duplicate rows in migration_history. "
                    f"row_count={current_count}, distinct_name_count="
                    f"{len(current_names)}, names={current_names_list}"
                )

                previous_count = current_count
                previous_names = current_names
    finally:
        _drop_migration_history()


# ---------------------------------------------------------------------------
# Property 8: Idempotent Re-Apply
# ---------------------------------------------------------------------------


@pytest.mark.django_db(transaction=True)
@given(
    filenames=st.lists(_filename_st, min_size=1, max_size=8, unique=True),
    rerun_count=st.integers(min_value=2, max_value=5),
)
@settings(max_examples=20, deadline=2000)
def test_repeated_apply_produces_no_duplicate_migration_history_rows(
    filenames: list[str], rerun_count: int
) -> None:
    """Property 8: re-apply is idempotent — ON CONFLICT prevents duplicates.

    For any set of migration files that are successfully applied on the
    first run, every subsequent run of ``apply_sql_migrations`` against
    the same files SHALL leave ``migration_history`` in exactly the same
    state — same row count, same ``migration_name`` set, same checksum
    per row. The ``INSERT ... ON CONFLICT (migration_name) DO NOTHING``
    primitive in ``_record_applied`` is the contract that makes this
    safe.

    **Validates: Requirements 1.8, 4.5, 8.6**
    """
    _drop_migration_history()
    _create_extended_migration_history()
    try:
        with tempfile.TemporaryDirectory(prefix="kf-rerun-") as tmp:
            tmp_dir = Path(tmp)
            _write_files(tmp_dir, sorted(filenames))

            # Establish the post-first-run baseline.
            _apply_against(tmp_dir)
            first_count = _row_count()
            first_names = _migration_names()

            assert first_count == len(filenames), (
                f"First run did not record one row per file: "
                f"row_count={first_count}, file_count={len(filenames)}, "
                f"names={first_names}"
            )
            assert sorted(first_names) == sorted(filenames), (
                f"First run recorded unexpected names. "
                f"recorded={sorted(first_names)}, "
                f"expected={sorted(filenames)}"
            )
            assert first_count == len(set(first_names)), (
                f"First run produced duplicate names: {first_names}"
            )

            # Subsequent runs: state must be byte-identical.
            for run_index in range(1, rerun_count):
                _apply_against(tmp_dir)
                rerun_count_now = _row_count()
                rerun_names = _migration_names()
                assert rerun_count_now == first_count, (
                    f"Run #{run_index + 1} produced duplicate rows: "
                    f"row_count={rerun_count_now} != "
                    f"first_run_count={first_count}. names_now="
                    f"{rerun_names}"
                )
                assert rerun_names == first_names, (
                    f"Run #{run_index + 1} mutated migration_name set. "
                    f"names_now={rerun_names}, "
                    f"first_run_names={first_names}"
                )
    finally:
        _drop_migration_history()
