-- ============================================================================
-- DEFERRED / FUTURE MIGRATION — DO NOT APPLY YET.
--
-- Spec:        .kiro/specs/multi-tenant-beanola-remediation/ (Task 7.4, R6.4)
-- Design ref:  design.md §3b "Optional `is_current` column (documented, deferred)"
-- Status:      AUTHORED ONLY. Never applied to Neon or production from this
--              environment. Lives under backend/scripts/future/ so the
--              container-startup runner (apply_sql_migrations) — which scans
--              ONLY the top level of backend/scripts/ and does not recurse —
--              cannot pick it up as an active migration. The schema-drift
--              checker (check_schema_drift) is likewise non-recursive, so this
--              file is invisible to both sweeps until an operator deliberately
--              promotes it to the top level.
--
-- Why deferred:
--   V1 of the Official_Document lifecycle (Task 7.3, complete) derives the
--   "Current_Official_Version" BY QUERY — the latest non-deleted
--   `system_generated = true` `application_documents` row for an
--   `(application_id, document_type)` pair, ordered by `uploaded_at` desc.
--   That keeps schema churn to zero while the lifecycle is proven in
--   production. This file is the drift-resistant upgrade: it makes "current"
--   an explicit, DB-enforced flag instead of a derived query, guaranteeing at
--   most one current system-generated document per (application, type) via a
--   partial unique index.
--
-- Promotion procedure (when the V1 query-derived lifecycle is proven):
--   1. Move this file to the top level of backend/scripts/ keeping the
--      `2026_06_08_05_` ordering prefix (it sorts after the tenant migrations
--      and the institution_document_profiles / communication_templates
--      migrations referenced in design.md §"Database Schema").
--   2. Add its sibling `*_rollback.sql` (the rollback-pairing property test in
--      backend/tests/property/test_rollback_pairing.py requires every
--      top-level forward script to ship with one).
--   3. Validate on a Neon branch first (create_branch → dry-run discovery →
--      apply → re-apply no-op) per .kiro/steering/infrastructure.md, then copy
--      to production via the deploy/RUNBOOK.md path. Never apply to production
--      as the first step.
--   4. Wire the generator change described in the "Generator behaviour" note
--      below in the SAME change so the flag is maintained on every write.
--
-- This script is additive and idempotent: ADD COLUMN IF NOT EXISTS,
-- backfill UPDATE scoped by WHERE, and CREATE UNIQUE INDEX IF NOT EXISTS only.
-- No DROP, no table rewrite, no destructive statement.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Additive column. Default true so every existing row (and any row written
--    by code that predates the generator change) is treated as current — this
--    matches the V1 query-derived behaviour, where the most recent non-deleted
--    system_generated row is the current one.
-- ----------------------------------------------------------------------------
ALTER TABLE application_documents
    ADD COLUMN IF NOT EXISTS is_current boolean NOT NULL DEFAULT true;

-- ----------------------------------------------------------------------------
-- 2. Best-effort backfill (idempotent, re-runnable).
--    Bring the new flag in line with the V1 "current = latest non-deleted
--    system_generated by uploaded_at" rule for EXISTING data, so promoting the
--    column does not retroactively mark several historical documents current.
--
--    a) Demote every system_generated row to is_current = false.
--    b) Promote only the single newest non-deleted system_generated row per
--       (application_id, document_type) back to is_current = true.
--
--    Non-system rows keep the default true (the partial index below ignores
--    them, so their flag is inert).
-- ----------------------------------------------------------------------------
UPDATE application_documents
SET is_current = false
WHERE system_generated = true
  AND is_current = true;

UPDATE application_documents AS d
SET is_current = true
FROM (
    SELECT DISTINCT ON (application_id, document_type) id
    FROM application_documents
    WHERE system_generated = true
      AND (verification_status IS DISTINCT FROM 'deleted')
    ORDER BY application_id, document_type, uploaded_at DESC, id DESC
) AS current_rows
WHERE d.id = current_rows.id
  AND d.is_current = false;

-- ----------------------------------------------------------------------------
-- 3. Partial unique index — the drift-resistant guarantee.
--    At most ONE current system-generated document per (application, type).
--    Scoped to system_generated AND is_current so it never constrains
--    student-uploaded documents or superseded/deleted prior versions.
--
--    NOTE on concurrency: when promoting on a large production table, prefer
--    `CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS` (the runner's split-phase
--    autocommit path handles CONCURRENTLY). The plain form is kept here for
--    clarity on Neon branch validation, where table size is small. Choose one
--    form at promotion time.
-- ----------------------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS uq_application_documents_current_system
    ON application_documents (application_id, document_type)
    WHERE system_generated = true AND is_current = true;

-- ----------------------------------------------------------------------------
-- Generator behaviour to wire in alongside this migration (NOT done in V1):
--
--   In backend/apps/applications/tasks/pdf_generation.py
--   `_generate_official_document_task`, when a NEW Official_Document supersedes
--   a prior current one for the same (application_id, document_type):
--
--     1. Within the same transaction that inserts the new row, flip the prior
--        current row: `UPDATE application_documents SET is_current = false
--        WHERE application_id = %s AND document_type = %s
--          AND system_generated = true AND is_current = true`.
--     2. Insert the new row with is_current = true.
--
--   The partial unique index makes step 2 fail loudly if step 1 was skipped,
--   converting a silent drift bug into a hard, observable error. The reuse
--   path (fingerprint unchanged → return existing) writes nothing and so
--   leaves is_current untouched. `verification_status = "deleted"` documents
--   are excluded from the index predicate, so soft-deleting the current row
--   does not block a future insert.
-- ----------------------------------------------------------------------------
